package com.oathbound.client.model;

import com.oathbound.client.render.Renderers;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

import java.util.HashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Supplier;

/** GENERATED by tools/oath/creatures.py: geometry for every Oathbound creature. Do not edit by hand. */
public final class ModelDefs {
    private ModelDefs() {}

    private static final Map<String, String[]> PATHS = new HashMap<>();

    /** Registers every layer with the given sink (the layer-definition event). */
    public static void register(BiConsumer<ModelLayerLocation, Supplier<LayerDefinition>> sink) {
        sink.accept(Renderers.layer("lanternmoth"), ModelDefs::lanternmoth);
        sink.accept(Renderers.layer("gloamling"), ModelDefs::gloamling);
        sink.accept(Renderers.layer("forsworn_knight"), ModelDefs::forsworn_knight);
        sink.accept(Renderers.layer("barrow_wight"), ModelDefs::barrow_wight);
        sink.accept(Renderers.layer("animated_tome"), ModelDefs::animated_tome);
        sink.accept(Renderers.layer("veilhound"), ModelDefs::veilhound);
        sink.accept(Renderers.layer("spectral_housecarl"), ModelDefs::spectral_housecarl);
        sink.accept(Renderers.layer("sir_caldris"), ModelDefs::sir_caldris);
        sink.accept(Renderers.layer("archmage_veyl"), ModelDefs::archmage_veyl);
        sink.accept(Renderers.layer("hrodgar"), ModelDefs::hrodgar);
        sink.accept(Renderers.layer("morvane"), ModelDefs::morvane);
        sink.accept(Renderers.layer("crown_blade"), ModelDefs::crown_blade);
        sink.accept(Renderers.layer("glimmerfawn"), ModelDefs::glimmerfawn);
        sink.accept(Renderers.layer("duskhare"), ModelDefs::duskhare);
        sink.accept(Renderers.layer("mossback_tortoise"), ModelDefs::mossback_tortoise);
        sink.accept(Renderers.layer("lumen_beetle"), ModelDefs::lumen_beetle);
        sink.accept(Renderers.layer("tidewader"), ModelDefs::tidewader);
        sink.accept(Renderers.layer("thornback_boar"), ModelDefs::thornback_boar);
        sink.accept(Renderers.layer("stonewarden"), ModelDefs::stonewarden);
        sink.accept(Renderers.layer("runewisp"), ModelDefs::runewisp);
        sink.accept(Renderers.layer("drowned_choirmonk"), ModelDefs::drowned_choirmonk);
        sink.accept(Renderers.layer("mire_hag"), ModelDefs::mire_hag);
        sink.accept(Renderers.layer("grave_crawler"), ModelDefs::grave_crawler);
        sink.accept(Renderers.layer("gloam_stalker"), ModelDefs::gloam_stalker);
        sink.accept(Renderers.layer("shade_wraith"), ModelDefs::shade_wraith);
        sink.accept(Renderers.layer("lumenite_mite"), ModelDefs::lumenite_mite);
        sink.accept(Renderers.layer("ashen_revenant"), ModelDefs::ashen_revenant);
        sink.accept(Renderers.layer("elderhorn"), ModelDefs::elderhorn);
        sink.accept(Renderers.layer("bog_mother"), ModelDefs::bog_mother);
        sink.accept(Renderers.layer("cinder_colossus"), ModelDefs::cinder_colossus);
    }

    /** The chain of child names from the model root to {@code part}, or null if there is none. */
    public static String[] path(String model, String part) {
        return PATHS.get(model + "/" + part);
    }

    private static void p(String key, String... path) {
        PATHS.put(key, path);
    }

    static {
        p("lanternmoth/body", "hull", "body");
        p("lanternmoth/head", "hull", "body", "head");
        p("lanternmoth/antenna_l", "hull", "body", "head", "antenna_l");
        p("lanternmoth/antenna_r", "hull", "body", "head", "antenna_r");
        p("lanternmoth/abdomen", "hull", "body", "abdomen");
        p("lanternmoth/left_wing", "hull", "body", "left_wing");
        p("lanternmoth/right_wing", "hull", "body", "right_wing");
        p("gloamling/left_leg", "hull", "left_leg");
        p("gloamling/right_leg", "hull", "right_leg");
        p("gloamling/body", "hull", "body");
        p("gloamling/head", "hull", "body", "head");
        p("gloamling/left_arm", "hull", "body", "left_arm");
        p("gloamling/right_arm", "hull", "body", "right_arm");
        p("gloamling/tail", "hull", "body", "tail");
        p("forsworn_knight/left_leg", "hull", "left_leg");
        p("forsworn_knight/right_leg", "hull", "right_leg");
        p("forsworn_knight/body", "hull", "body");
        p("forsworn_knight/head", "hull", "body", "head");
        p("forsworn_knight/left_arm", "hull", "body", "left_arm");
        p("forsworn_knight/right_arm", "hull", "body", "right_arm");
        p("forsworn_knight/cape", "hull", "body", "cape");
        p("barrow_wight/body", "hull", "body");
        p("barrow_wight/head", "hull", "body", "head");
        p("barrow_wight/left_arm", "hull", "body", "left_arm");
        p("barrow_wight/right_arm", "hull", "body", "right_arm");
        p("barrow_wight/tail1", "hull", "body", "tail1");
        p("barrow_wight/tail2", "hull", "body", "tail1", "tail2");
        p("animated_tome/spine", "hull", "spine");
        p("animated_tome/cover_left", "hull", "spine", "cover_left");
        p("animated_tome/cover_right", "hull", "spine", "cover_right");
        p("animated_tome/pages", "hull", "spine", "pages");
        p("veilhound/body", "hull", "body");
        p("veilhound/head", "hull", "body", "head");
        p("veilhound/jaw", "hull", "body", "head", "jaw");
        p("veilhound/leg_fl", "hull", "body", "leg_fl");
        p("veilhound/leg_fr", "hull", "body", "leg_fr");
        p("veilhound/leg_bl", "hull", "body", "leg_bl");
        p("veilhound/leg_br", "hull", "body", "leg_br");
        p("veilhound/tail", "hull", "body", "tail");
        p("spectral_housecarl/left_leg", "hull", "left_leg");
        p("spectral_housecarl/right_leg", "hull", "right_leg");
        p("spectral_housecarl/body", "hull", "body");
        p("spectral_housecarl/head", "hull", "body", "head");
        p("spectral_housecarl/left_arm", "hull", "body", "left_arm");
        p("spectral_housecarl/shield", "hull", "body", "left_arm", "shield");
        p("spectral_housecarl/right_arm", "hull", "body", "right_arm");
        p("sir_caldris/left_leg", "hull", "left_leg");
        p("sir_caldris/right_leg", "hull", "right_leg");
        p("sir_caldris/body", "hull", "body");
        p("sir_caldris/head", "hull", "body", "head");
        p("sir_caldris/left_arm", "hull", "body", "left_arm");
        p("sir_caldris/shield", "hull", "body", "left_arm", "shield");
        p("sir_caldris/right_arm", "hull", "body", "right_arm");
        p("sir_caldris/anchor", "hull", "body", "right_arm", "anchor");
        p("sir_caldris/cape", "hull", "body", "cape");
        p("archmage_veyl/body", "hull", "body");
        p("archmage_veyl/head", "hull", "body", "head");
        p("archmage_veyl/halo", "hull", "body", "head", "halo");
        p("archmage_veyl/left_arm", "hull", "body", "left_arm");
        p("archmage_veyl/right_arm", "hull", "body", "right_arm");
        p("archmage_veyl/staff", "hull", "body", "right_arm", "staff");
        p("archmage_veyl/skirt", "hull", "body", "skirt");
        p("archmage_veyl/skirt2", "hull", "body", "skirt", "skirt2");
        p("archmage_veyl/left_leg", "hull", "body", "left_leg");
        p("archmage_veyl/right_leg", "hull", "body", "right_leg");
        p("hrodgar/left_leg", "hull", "left_leg");
        p("hrodgar/right_leg", "hull", "right_leg");
        p("hrodgar/body", "hull", "body");
        p("hrodgar/head", "hull", "body", "head");
        p("hrodgar/left_arm", "hull", "body", "left_arm");
        p("hrodgar/right_arm", "hull", "body", "right_arm");
        p("hrodgar/flail_chain", "hull", "body", "right_arm", "flail_chain");
        p("hrodgar/flail_head", "hull", "body", "right_arm", "flail_chain", "flail_head");
        p("hrodgar/cape", "hull", "body", "cape");
        p("morvane/left_leg", "hull", "left_leg");
        p("morvane/right_leg", "hull", "right_leg");
        p("morvane/body", "hull", "body");
        p("morvane/head", "hull", "body", "head");
        p("morvane/crown", "hull", "body", "head", "crown");
        p("morvane/left_arm", "hull", "body", "left_arm");
        p("morvane/right_arm", "hull", "body", "right_arm");
        p("morvane/sword", "hull", "body", "right_arm", "sword");
        p("morvane/cape", "hull", "body", "cape");
        p("crown_blade/blade", "hull", "blade");
        p("glimmerfawn/body", "hull", "body");
        p("glimmerfawn/head", "hull", "body", "head");
        p("glimmerfawn/ear_l", "hull", "body", "head", "ear_l");
        p("glimmerfawn/ear_r", "hull", "body", "head", "ear_r");
        p("glimmerfawn/leg_fl", "hull", "body", "leg_fl");
        p("glimmerfawn/leg_fr", "hull", "body", "leg_fr");
        p("glimmerfawn/leg_bl", "hull", "body", "leg_bl");
        p("glimmerfawn/leg_br", "hull", "body", "leg_br");
        p("glimmerfawn/tail", "hull", "body", "tail");
        p("duskhare/body", "hull", "body");
        p("duskhare/head", "hull", "body", "head");
        p("duskhare/ear_l", "hull", "body", "head", "ear_l");
        p("duskhare/ear_r", "hull", "body", "head", "ear_r");
        p("duskhare/leg_fl", "hull", "body", "leg_fl");
        p("duskhare/leg_fr", "hull", "body", "leg_fr");
        p("duskhare/leg_bl", "hull", "body", "leg_bl");
        p("duskhare/leg_br", "hull", "body", "leg_br");
        p("duskhare/tail", "hull", "body", "tail");
        p("mossback_tortoise/body", "hull", "body");
        p("mossback_tortoise/head", "hull", "body", "head");
        p("mossback_tortoise/leg_fl", "hull", "body", "leg_fl");
        p("mossback_tortoise/leg_fr", "hull", "body", "leg_fr");
        p("mossback_tortoise/leg_bl", "hull", "body", "leg_bl");
        p("mossback_tortoise/leg_br", "hull", "body", "leg_br");
        p("mossback_tortoise/tail", "hull", "body", "tail");
        p("lumen_beetle/body", "hull", "body");
        p("lumen_beetle/head", "hull", "body", "head");
        p("lumen_beetle/leg_0", "hull", "body", "leg_0");
        p("lumen_beetle/leg_1", "hull", "body", "leg_1");
        p("lumen_beetle/leg_2", "hull", "body", "leg_2");
        p("lumen_beetle/leg_3", "hull", "body", "leg_3");
        p("lumen_beetle/leg_4", "hull", "body", "leg_4");
        p("lumen_beetle/leg_5", "hull", "body", "leg_5");
        p("tidewader/body", "hull", "body");
        p("tidewader/neck", "hull", "body", "neck");
        p("tidewader/head", "hull", "body", "neck", "head");
        p("tidewader/left_wing", "hull", "body", "left_wing");
        p("tidewader/right_wing", "hull", "body", "right_wing");
        p("tidewader/left_leg", "hull", "body", "left_leg");
        p("tidewader/right_leg", "hull", "body", "right_leg");
        p("tidewader/tail", "hull", "body", "tail");
        p("thornback_boar/body", "hull", "body");
        p("thornback_boar/head", "hull", "body", "head");
        p("thornback_boar/ear_l", "hull", "body", "head", "ear_l");
        p("thornback_boar/ear_r", "hull", "body", "head", "ear_r");
        p("thornback_boar/leg_fl", "hull", "body", "leg_fl");
        p("thornback_boar/leg_fr", "hull", "body", "leg_fr");
        p("thornback_boar/leg_bl", "hull", "body", "leg_bl");
        p("thornback_boar/leg_br", "hull", "body", "leg_br");
        p("thornback_boar/tail", "hull", "body", "tail");
        p("stonewarden/left_leg", "hull", "left_leg");
        p("stonewarden/right_leg", "hull", "right_leg");
        p("stonewarden/body", "hull", "body");
        p("stonewarden/head", "hull", "body", "head");
        p("stonewarden/left_arm", "hull", "body", "left_arm");
        p("stonewarden/right_arm", "hull", "body", "right_arm");
        p("runewisp/body", "hull", "body");
        p("runewisp/orbit_0", "hull", "body", "orbit_0");
        p("runewisp/orbit_1", "hull", "body", "orbit_1");
        p("runewisp/orbit_2", "hull", "body", "orbit_2");
        p("drowned_choirmonk/left_leg", "hull", "left_leg");
        p("drowned_choirmonk/right_leg", "hull", "right_leg");
        p("drowned_choirmonk/body", "hull", "body");
        p("drowned_choirmonk/head", "hull", "body", "head");
        p("drowned_choirmonk/left_arm", "hull", "body", "left_arm");
        p("drowned_choirmonk/right_arm", "hull", "body", "right_arm");
        p("drowned_choirmonk/robe", "hull", "body", "robe");
        p("mire_hag/left_leg", "hull", "left_leg");
        p("mire_hag/right_leg", "hull", "right_leg");
        p("mire_hag/body", "hull", "body");
        p("mire_hag/head", "hull", "body", "head");
        p("mire_hag/left_arm", "hull", "body", "left_arm");
        p("mire_hag/right_arm", "hull", "body", "right_arm");
        p("mire_hag/robe", "hull", "body", "robe");
        p("grave_crawler/body", "hull", "body");
        p("grave_crawler/head", "hull", "body", "head");
        p("grave_crawler/leg_0", "hull", "body", "leg_0");
        p("grave_crawler/leg_1", "hull", "body", "leg_1");
        p("grave_crawler/leg_2", "hull", "body", "leg_2");
        p("grave_crawler/leg_3", "hull", "body", "leg_3");
        p("grave_crawler/leg_4", "hull", "body", "leg_4");
        p("grave_crawler/leg_5", "hull", "body", "leg_5");
        p("gloam_stalker/body", "hull", "body");
        p("gloam_stalker/head", "hull", "body", "head");
        p("gloam_stalker/ear_l", "hull", "body", "head", "ear_l");
        p("gloam_stalker/ear_r", "hull", "body", "head", "ear_r");
        p("gloam_stalker/jaw", "hull", "body", "head", "jaw");
        p("gloam_stalker/leg_fl", "hull", "body", "leg_fl");
        p("gloam_stalker/leg_fr", "hull", "body", "leg_fr");
        p("gloam_stalker/leg_bl", "hull", "body", "leg_bl");
        p("gloam_stalker/leg_br", "hull", "body", "leg_br");
        p("gloam_stalker/tail", "hull", "body", "tail");
        p("shade_wraith/body", "hull", "body");
        p("shade_wraith/head", "hull", "body", "head");
        p("shade_wraith/cloak", "hull", "body", "cloak");
        p("shade_wraith/left_arm", "hull", "body", "left_arm");
        p("shade_wraith/right_arm", "hull", "body", "right_arm");
        p("lumenite_mite/body", "hull", "body");
        p("lumenite_mite/head", "hull", "body", "head");
        p("lumenite_mite/leg_0", "hull", "body", "leg_0");
        p("lumenite_mite/leg_1", "hull", "body", "leg_1");
        p("lumenite_mite/leg_2", "hull", "body", "leg_2");
        p("lumenite_mite/leg_3", "hull", "body", "leg_3");
        p("lumenite_mite/leg_4", "hull", "body", "leg_4");
        p("lumenite_mite/leg_5", "hull", "body", "leg_5");
        p("ashen_revenant/left_leg", "hull", "left_leg");
        p("ashen_revenant/right_leg", "hull", "right_leg");
        p("ashen_revenant/body", "hull", "body");
        p("ashen_revenant/head", "hull", "body", "head");
        p("ashen_revenant/left_arm", "hull", "body", "left_arm");
        p("ashen_revenant/right_arm", "hull", "body", "right_arm");
        p("elderhorn/body", "hull", "body");
        p("elderhorn/head", "hull", "body", "head");
        p("elderhorn/ear_l", "hull", "body", "head", "ear_l");
        p("elderhorn/ear_r", "hull", "body", "head", "ear_r");
        p("elderhorn/leg_fl", "hull", "body", "leg_fl");
        p("elderhorn/leg_fr", "hull", "body", "leg_fr");
        p("elderhorn/leg_bl", "hull", "body", "leg_bl");
        p("elderhorn/leg_br", "hull", "body", "leg_br");
        p("elderhorn/tail", "hull", "body", "tail");
        p("bog_mother/left_leg", "hull", "left_leg");
        p("bog_mother/right_leg", "hull", "right_leg");
        p("bog_mother/body", "hull", "body");
        p("bog_mother/head", "hull", "body", "head");
        p("bog_mother/left_arm", "hull", "body", "left_arm");
        p("bog_mother/right_arm", "hull", "body", "right_arm");
        p("bog_mother/robe", "hull", "body", "robe");
        p("cinder_colossus/left_leg", "hull", "left_leg");
        p("cinder_colossus/right_leg", "hull", "right_leg");
        p("cinder_colossus/body", "hull", "body");
        p("cinder_colossus/head", "hull", "body", "head");
        p("cinder_colossus/left_arm", "hull", "body", "left_arm");
        p("cinder_colossus/right_arm", "hull", "body", "right_arm");
    }

    private static LayerDefinition lanternmoth() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 7).addBox(-1.5F, -1.5F, -2.0F, 3.0F, 3.0F, 4.0F).texOffs(0, 14).addBox(-2.0F, -2.0F, -2.6F, 4.0F, 4.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(20, 14).addBox(-1.0F, -1.0F, -2.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -0.5F, -2.6F, 0.25F, 0.0F, 0.0F));
        PartDefinition p_antenna_l = p_head.addOrReplaceChild("antenna_l", CubeListBuilder.create().texOffs(44, 14).addBox(0.0F, -4.0F, 0.0F, 2.0F, 4.0F, 0.0F), PartPose.offsetAndRotation(0.5F, -1.0F, -1.5F, -0.35F, 0.0F, 0.35F));
        PartDefinition p_antenna_r = p_head.addOrReplaceChild("antenna_r", CubeListBuilder.create().texOffs(48, 14).addBox(-2.0F, -4.0F, 0.0F, 2.0F, 4.0F, 0.0F), PartPose.offsetAndRotation(-0.5F, -1.0F, -1.5F, -0.35F, 0.0F, -0.35F));
        PartDefinition p_abdomen = p_body.addOrReplaceChild("abdomen", CubeListBuilder.create().texOffs(10, 14).addBox(-1.5F, -1.5F, 0.0F, 3.0F, 3.0F, 2.0F).texOffs(28, 14).addBox(-1.5F, -1.5F, 2.0F, 3.0F, 3.0F, 1.0F, new CubeDeformation(0.1F)).texOffs(36, 14).addBox(-1.0F, -1.0F, 3.0F, 2.0F, 2.0F, 2.0F).texOffs(52, 14).addBox(-0.5F, -0.5F, 5.0F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 2.0F, -0.3F, 0.0F, 0.0F));
        PartDefinition p_left_wing = p_body.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(0, 0).addBox(0.0F, 0.0F, -4.0F, 9.0F, 0.0F, 7.0F).texOffs(14, 7).addBox(0.0F, 0.2F, 1.0F, 7.0F, 0.0F, 5.0F), PartPose.offsetAndRotation(1.5F, -1.0F, -0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_wing = p_body.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(32, 0).addBox(-9.0F, 0.0F, -4.0F, 9.0F, 0.0F, 7.0F).texOffs(38, 7).addBox(-7.0F, 0.2F, 1.0F, 7.0F, 0.0F, 5.0F), PartPose.offsetAndRotation(-1.5F, -1.0F, -0.5F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    private static LayerDefinition gloamling() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(14, 10).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F).texOffs(24, 17).addBox(-1.0F, 4.0F, -2.0F, 2.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(1.5F, -5.0F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(22, 10).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F).texOffs(30, 17).addBox(-1.0F, 4.0F, -2.0F, 2.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-1.5F, -5.0F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(20, 0).addBox(-2.5F, -6.0F, -1.5F, 5.0F, 6.0F, 3.0F).texOffs(30, 10).addBox(-1.5F, -5.0F, -2.0F, 3.0F, 4.0F, 1.0F).texOffs(58, 10).addBox(-0.5F, -6.5F, 1.5F, 1.0F, 2.0F, 1.0F).texOffs(36, 17).addBox(-0.5F, -3.5F, 1.5F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -5.0F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-2.5F, -5.0F, -2.5F, 5.0F, 5.0F, 5.0F).texOffs(0, 17).addBox(-3.5F, -3.5F, -0.5F, 1.0F, 2.0F, 1.0F).texOffs(4, 17).addBox(2.5F, -3.5F, -0.5F, 1.0F, 2.0F, 1.0F).texOffs(8, 17).addBox(-3.0F, -6.0F, -1.0F, 1.0F, 2.0F, 1.0F).texOffs(12, 17).addBox(2.0F, -6.0F, -1.0F, 1.0F, 2.0F, 1.0F).texOffs(40, 17).addBox(-3.5F, -7.0F, 0.0F, 1.0F, 1.0F, 1.0F).texOffs(44, 17).addBox(2.5F, -7.0F, 0.0F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -6.0F, -0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(36, 0).addBox(0.0F, -0.5F, -1.0F, 2.0F, 7.0F, 2.0F).texOffs(46, 10).addBox(0.0F, 6.5F, -1.5F, 2.0F, 2.0F, 1.0F).texOffs(16, 17).addBox(0.5F, 6.5F, 0.0F, 1.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(2.5F, -5.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(44, 0).addBox(-2.0F, -0.5F, -1.0F, 2.0F, 7.0F, 2.0F).texOffs(52, 10).addBox(-2.0F, 6.5F, -1.5F, 2.0F, 2.0F, 1.0F).texOffs(20, 17).addBox(-1.5F, 6.5F, 0.0F, 1.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(-2.5F, -5.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(0, 10).addBox(-0.5F, -0.5F, 0.0F, 1.0F, 1.0F, 6.0F).texOffs(38, 10).addBox(-1.0F, -1.0F, 6.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -1.0F, 1.5F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    private static LayerDefinition forsworn_knight() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(46, 0).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 13.0F, 4.0F).texOffs(18, 41).addBox(-2.5F, 5.0F, -2.6F, 5.0F, 2.0F, 1.0F).texOffs(54, 41).addBox(-2.0F, 11.0F, -3.0F, 4.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(2.2F, -13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(62, 0).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 13.0F, 4.0F).texOffs(30, 41).addBox(-2.5F, 5.0F, -2.6F, 5.0F, 2.0F, 1.0F).texOffs(64, 41).addBox(-2.0F, 11.0F, -3.0F, 4.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(-2.2F, -13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.5F, -12.0F, -2.5F, 9.0F, 12.0F, 5.0F).texOffs(94, 17).addBox(-5.0F, -2.0F, -3.0F, 10.0F, 2.0F, 6.0F).texOffs(96, 33).addBox(-4.0F, 0.0F, -3.2F, 8.0F, 4.0F, 1.0F).texOffs(0, 41).addBox(-4.0F, 0.0F, 2.2F, 8.0F, 4.0F, 1.0F).texOffs(76, 33).addBox(-3.0F, -13.0F, -2.0F, 6.0F, 1.0F, 4.0F), PartPose.offsetAndRotation(0.0F, -13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(16, 17).addBox(-3.5F, -8.0F, -3.5F, 7.0F, 8.0F, 7.0F).texOffs(40, 33).addBox(-0.5F, -9.0F, -3.5F, 1.0F, 1.0F, 7.0F).texOffs(42, 41).addBox(-2.5F, -2.0F, -4.0F, 5.0F, 2.0F, 1.0F).texOffs(56, 33).addBox(-0.5F, -11.0F, -1.5F, 1.0F, 2.0F, 6.0F).texOffs(88, 17).addBox(-0.5F, -10.0F, 4.5F, 1.0F, 7.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -12.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(44, 17).addBox(-1.5F, -2.5F, -3.0F, 5.0F, 4.0F, 6.0F).texOffs(108, 0).addBox(-1.0F, -1.0F, -2.0F, 4.0F, 12.0F, 4.0F).texOffs(0, 33).addBox(-1.5F, 8.0F, -2.5F, 5.0F, 3.0F, 5.0F), PartPose.offsetAndRotation(6.0F, -11.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(66, 17).addBox(-3.5F, -2.5F, -3.0F, 5.0F, 4.0F, 6.0F).texOffs(0, 17).addBox(-3.0F, -1.0F, -2.0F, 4.0F, 12.0F, 4.0F).texOffs(20, 33).addBox(-3.5F, 8.0F, -2.5F, 5.0F, 3.0F, 5.0F).texOffs(78, 0).addBox(-1.5F, 9.0F, -18.0F, 1.0F, 2.0F, 14.0F).texOffs(70, 33).addBox(-2.0F, 7.0F, -4.5F, 2.0F, 6.0F, 1.0F).texOffs(74, 41).addBox(-1.5F, 9.5F, -4.0F, 1.0F, 1.0F, 2.0F).texOffs(80, 41).addBox(-2.0F, 9.0F, 2.5F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(-6.0F, -11.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_cape = p_body.addOrReplaceChild("cape", CubeListBuilder.create().texOffs(28, 0).addBox(-4.5F, 0.0F, 0.0F, 9.0F, 17.0F, 0.0F), PartPose.offsetAndRotation(0.0F, -12.0F, 2.6F, 0.08F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    private static LayerDefinition barrow_wight() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -11.0F, -2.5F, 8.0F, 11.0F, 5.0F).texOffs(0, 16).addBox(-5.0F, -11.5F, -3.0F, 10.0F, 3.0F, 6.0F).texOffs(84, 16).addBox(-3.0F, -12.0F, -3.2F, 6.0F, 1.0F, 5.0F), PartPose.offsetAndRotation(0.0F, -15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(26, 0).addBox(-3.5F, -7.0F, -3.5F, 7.0F, 7.0F, 7.0F).texOffs(106, 16).addBox(-2.5F, -8.0F, -2.0F, 5.0F, 1.0F, 5.0F).texOffs(60, 16).addBox(-3.0F, -6.0F, 3.5F, 6.0F, 7.0F, 0.0F).texOffs(32, 16).addBox(-3.5F, -6.0F, -3.5F, 7.0F, 1.0F, 7.0F, new CubeDeformation(0.25F)), PartPose.offsetAndRotation(0.0F, -11.5F, -0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(80, 0).addBox(-1.0F, -1.0F, -1.5F, 3.0F, 9.0F, 3.0F).texOffs(0, 25).addBox(-0.5F, 8.0F, -1.0F, 2.0F, 3.0F, 2.0F).texOffs(16, 25).addBox(-0.5F, 11.0F, -1.0F, 2.0F, 2.0F, 1.0F).texOffs(72, 16).addBox(-1.0F, 4.0F, 1.5F, 3.0F, 7.0F, 0.0F), PartPose.offsetAndRotation(4.5F, -10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(92, 0).addBox(-2.0F, -1.0F, -1.5F, 3.0F, 9.0F, 3.0F).texOffs(8, 25).addBox(-1.5F, 8.0F, -1.0F, 2.0F, 3.0F, 2.0F).texOffs(22, 25).addBox(-1.5F, 11.0F, -1.0F, 2.0F, 2.0F, 1.0F).texOffs(78, 16).addBox(-2.0F, 4.0F, 1.5F, 3.0F, 7.0F, 0.0F), PartPose.offsetAndRotation(-4.5F, -10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail1 = p_body.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(54, 0).addBox(-4.0F, 0.0F, -2.5F, 8.0F, 8.0F, 5.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail2 = p_tail1.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(104, 0).addBox(-3.0F, 0.0F, -2.0F, 6.0F, 7.0F, 4.0F), PartPose.offsetAndRotation(0.0F, 8.0F, 0.5F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 32);
    }

    private static LayerDefinition animated_tome() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_spine = p_hull.addOrReplaceChild("spine", CubeListBuilder.create().texOffs(30, 13).addBox(-1.0F, -0.5F, -4.5F, 2.0F, 1.0F, 9.0F).texOffs(52, 23).addBox(-0.5F, 0.5F, 1.5F, 0.0F, 5.0F, 1.0F).texOffs(54, 23).addBox(0.5F, 0.5F, -0.5F, 0.0F, 4.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_cover_left = p_spine.addOrReplaceChild("cover_left", CubeListBuilder.create().texOffs(16, 0).addBox(0.0F, -0.5F, -4.5F, 6.0F, 1.0F, 9.0F).texOffs(0, 23).addBox(0.3F, -1.5F, -4.0F, 5.0F, 1.0F, 8.0F).texOffs(56, 23).addBox(6.0F, -0.5F, -1.0F, 1.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_cover_right = p_spine.addOrReplaceChild("cover_right", CubeListBuilder.create().texOffs(0, 13).addBox(-6.0F, -0.5F, -4.5F, 6.0F, 1.0F, 9.0F).texOffs(26, 23).addBox(-5.3F, -1.5F, -4.0F, 5.0F, 1.0F, 8.0F).texOffs(0, 32).addBox(-7.0F, -0.5F, -1.0F, 1.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(-1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_pages = p_spine.addOrReplaceChild("pages", CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, -6.0F, -3.5F, 1.0F, 6.0F, 7.0F), PartPose.offsetAndRotation(0.0F, -0.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    private static LayerDefinition veilhound() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.5F, -4.0F, -7.0F, 7.0F, 8.0F, 7.0F).texOffs(28, 0).addBox(-3.0F, -3.5F, 0.0F, 6.0F, 6.0F, 7.0F).texOffs(40, 15).addBox(-3.5F, -5.0F, -7.5F, 7.0F, 3.0F, 5.0F).texOffs(60, 39).addBox(-0.5F, -8.0F, -6.0F, 1.0F, 3.0F, 1.0F).texOffs(60, 33).addBox(-0.5F, -8.5F, -3.5F, 1.0F, 4.0F, 1.0F).texOffs(0, 43).addBox(-0.5F, -7.0F, -1.0F, 1.0F, 3.0F, 1.0F).texOffs(4, 43).addBox(-0.5F, -6.0F, 2.0F, 1.0F, 2.0F, 1.0F).texOffs(8, 43).addBox(-2.5F, -6.5F, -5.0F, 1.0F, 2.0F, 1.0F).texOffs(12, 43).addBox(1.5F, -6.5F, -5.0F, 1.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 15).addBox(-3.0F, -3.0F, -5.0F, 6.0F, 5.0F, 5.0F).texOffs(48, 25).addBox(-2.0F, -1.0F, -9.0F, 4.0F, 3.0F, 4.0F).texOffs(48, 39).addBox(-3.0F, -5.5F, -2.0F, 2.0F, 3.0F, 1.0F).texOffs(54, 39).addBox(1.0F, -5.5F, -2.0F, 2.0F, 3.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -2.0F, -7.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_jaw = p_head.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(0, 33).addBox(-2.0F, 0.0F, -4.0F, 4.0F, 2.0F, 4.0F), PartPose.offsetAndRotation(0.0F, 2.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fl = p_body.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(0, 25).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 5.0F, 3.0F).texOffs(28, 33).addBox(-1.0F, 5.0F, -1.0F, 2.0F, 3.0F, 2.0F).texOffs(0, 39).addBox(-1.5F, 8.0F, -2.0F, 3.0F, 1.0F, 3.0F), PartPose.offsetAndRotation(2.0F, 1.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fr = p_body.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(12, 25).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 5.0F, 3.0F).texOffs(36, 33).addBox(-1.0F, 5.0F, -1.0F, 2.0F, 3.0F, 2.0F).texOffs(12, 39).addBox(-1.5F, 8.0F, -2.0F, 3.0F, 1.0F, 3.0F), PartPose.offsetAndRotation(-2.0F, 1.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_bl = p_body.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(24, 25).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 5.0F, 3.0F).texOffs(44, 33).addBox(-1.0F, 5.0F, -1.0F, 2.0F, 3.0F, 2.0F).texOffs(24, 39).addBox(-1.5F, 8.0F, -2.0F, 3.0F, 1.0F, 3.0F), PartPose.offsetAndRotation(2.0F, 1.0F, 5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_br = p_body.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(36, 25).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 5.0F, 3.0F).texOffs(52, 33).addBox(-1.0F, 5.0F, -1.0F, 2.0F, 3.0F, 2.0F).texOffs(36, 39).addBox(-1.5F, 8.0F, -2.0F, 3.0F, 1.0F, 3.0F), PartPose.offsetAndRotation(-2.0F, 1.0F, 5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(22, 15).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 7.0F).texOffs(16, 33).addBox(-1.5F, -1.5F, 7.0F, 3.0F, 3.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -2.0F, 7.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    private static LayerDefinition spectral_housecarl() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(88, 0).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F).texOffs(90, 16).addBox(-2.5F, 8.0F, -2.5F, 5.0F, 4.0F, 5.0F), PartPose.offsetAndRotation(2.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(104, 0).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F).texOffs(0, 32).addBox(-2.5F, 8.0F, -2.5F, 5.0F, 4.0F, 5.0F), PartPose.offsetAndRotation(-2.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(64, 0).addBox(-4.0F, -12.0F, -2.0F, 8.0F, 12.0F, 4.0F).texOffs(88, 32).addBox(-4.5F, -1.5F, -2.5F, 9.0F, 2.0F, 5.0F).texOffs(20, 32).addBox(-4.5F, 0.5F, -2.5F, 9.0F, 3.0F, 5.0F).texOffs(58, 16).addBox(-5.0F, -12.5F, -3.0F, 10.0F, 3.0F, 6.0F), PartPose.offsetAndRotation(0.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F).texOffs(32, 41).addBox(-1.0F, -10.0F, -1.0F, 2.0F, 2.0F, 2.0F).texOffs(18, 41).addBox(-3.0F, -2.0F, -5.0F, 6.0F, 4.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 16).addBox(-1.0F, -2.0F, -2.0F, 4.0F, 12.0F, 4.0F).texOffs(48, 32).addBox(-1.5F, 5.0F, -2.5F, 5.0F, 3.0F, 5.0F), PartPose.offsetAndRotation(5.0F, -10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shield = p_left_arm.addOrReplaceChild("shield", CubeListBuilder.create().texOffs(32, 16).addBox(-6.0F, -6.0F, -3.5F, 12.0F, 12.0F, 1.0F).texOffs(40, 41).addBox(-1.5F, -1.5F, -4.5F, 3.0F, 3.0F, 1.0F), PartPose.offsetAndRotation(1.0F, 7.0F, 0.0F, 0.9F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(16, 16).addBox(-3.0F, -2.0F, -2.0F, 4.0F, 12.0F, 4.0F).texOffs(68, 32).addBox(-3.5F, 5.0F, -2.5F, 5.0F, 3.0F, 5.0F).texOffs(32, 0).addBox(-1.5F, 9.0F, -17.0F, 1.0F, 1.0F, 15.0F).texOffs(116, 32).addBox(-1.5F, 10.0F, -17.0F, 1.0F, 4.0F, 3.0F).texOffs(12, 41).addBox(-1.5F, 12.0F, -19.0F, 1.0F, 4.0F, 2.0F).texOffs(0, 41).addBox(-1.5F, 16.0F, -20.0F, 1.0F, 1.0F, 5.0F).texOffs(48, 41).addBox(-1.5F, 7.0F, -17.0F, 1.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(-5.0F, -10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    private static LayerDefinition sir_caldris() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(0, 22).addBox(-2.5F, 0.0F, -2.5F, 5.0F, 14.0F, 5.0F).texOffs(70, 70).addBox(-3.0F, 6.0F, -3.0F, 6.0F, 2.0F, 1.0F).texOffs(38, 54).addBox(-3.0F, 12.0F, -3.5F, 6.0F, 2.0F, 6.0F).texOffs(118, 70).addBox(1.5F, 3.0F, -3.0F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(2.5F, -14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(20, 22).addBox(-2.5F, 0.0F, -2.5F, 5.0F, 14.0F, 5.0F).texOffs(84, 70).addBox(-3.0F, 6.0F, -3.0F, 6.0F, 2.0F, 1.0F).texOffs(62, 54).addBox(-3.0F, 12.0F, -3.5F, 6.0F, 2.0F, 6.0F).texOffs(122, 70).addBox(-2.0F, 3.0F, -3.0F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-2.5F, -14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(94, 0).addBox(-5.0F, -13.0F, -3.0F, 10.0F, 13.0F, 6.0F).texOffs(0, 54).addBox(-5.5F, -2.0F, -3.5F, 11.0F, 2.0F, 7.0F).texOffs(44, 63).addBox(-5.0F, 0.0F, -3.5F, 10.0F, 5.0F, 1.0F).texOffs(66, 63).addBox(-5.0F, 0.0F, 2.5F, 10.0F, 5.0F, 1.0F).texOffs(0, 63).addBox(-4.0F, -14.5F, -2.5F, 8.0F, 2.0F, 5.0F).texOffs(106, 70).addBox(3.0F, -11.0F, -3.4F, 2.0F, 2.0F, 1.0F).texOffs(0, 75).addBox(-4.0F, -6.0F, -3.4F, 1.0F, 1.0F, 1.0F).texOffs(112, 70).addBox(-3.0F, -9.0F, 3.0F, 2.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(40, 22).addBox(-4.0F, -9.0F, -4.0F, 8.0F, 9.0F, 8.0F).texOffs(0, 41).addBox(-0.5F, -13.0F, -3.0F, 1.0F, 4.0F, 9.0F).texOffs(86, 54).addBox(-5.0F, -7.0F, -1.0F, 1.0F, 4.0F, 4.0F).texOffs(96, 54).addBox(4.0F, -7.0F, -1.0F, 1.0F, 4.0F, 4.0F), PartPose.offsetAndRotation(0.0F, -13.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(20, 41).addBox(-2.0F, -3.0F, -3.5F, 6.0F, 5.0F, 7.0F).texOffs(72, 22).addBox(-1.5F, -1.0F, -2.5F, 5.0F, 12.0F, 5.0F).texOffs(72, 41).addBox(-2.0F, 8.0F, -3.0F, 6.0F, 4.0F, 6.0F), PartPose.offsetAndRotation(7.0F, -11.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shield = p_left_arm.addOrReplaceChild("shield", CubeListBuilder.create().texOffs(8, 0).addBox(-6.5F, 0.0F, -8.0F, 13.0F, 1.0F, 20.0F).texOffs(30, 70).addBox(-1.5F, 1.0F, 0.0F, 3.0F, 1.0F, 3.0F).texOffs(98, 70).addBox(3.0F, 1.0F, 7.0F, 2.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(1.0F, 11.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(46, 41).addBox(-4.0F, -3.0F, -3.5F, 6.0F, 5.0F, 7.0F).texOffs(92, 22).addBox(-3.5F, -1.0F, -2.5F, 5.0F, 12.0F, 5.0F).texOffs(96, 41).addBox(-4.0F, 8.0F, -3.0F, 6.0F, 4.0F, 6.0F), PartPose.offsetAndRotation(-7.0F, -11.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_anchor = p_right_arm.addOrReplaceChild("anchor", CubeListBuilder.create().texOffs(0, 0).addBox(-1.0F, -7.0F, -1.0F, 2.0F, 20.0F, 2.0F).texOffs(50, 70).addBox(-4.0F, -4.0F, -1.0F, 8.0F, 1.0F, 2.0F).texOffs(42, 70).addBox(-1.5F, -10.0F, -0.5F, 3.0F, 3.0F, 1.0F).texOffs(0, 70).addBox(-6.0F, 12.0F, -1.5F, 12.0F, 2.0F, 3.0F).texOffs(26, 63).addBox(-7.0F, 8.0F, -1.0F, 2.0F, 5.0F, 2.0F).texOffs(34, 63).addBox(5.0F, 8.0F, -1.0F, 2.0F, 5.0F, 2.0F).texOffs(88, 63).addBox(-8.0F, 6.0F, -1.5F, 2.0F, 3.0F, 3.0F).texOffs(98, 63).addBox(6.0F, 6.0F, -1.5F, 2.0F, 3.0F, 3.0F).texOffs(36, 54).addBox(1.0F, 1.0F, 1.0F, 0.0F, 8.0F, 1.0F), PartPose.offsetAndRotation(-1.0F, 10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_cape = p_body.addOrReplaceChild("cape", CubeListBuilder.create().texOffs(74, 0).addBox(-5.0F, 0.0F, 0.0F, 10.0F, 20.0F, 0.0F).texOffs(108, 63).addBox(-4.0F, 18.0F, 0.05F, 1.0F, 6.0F, 0.0F).texOffs(42, 63).addBox(1.0F, 17.0F, 0.05F, 1.0F, 7.0F, 0.0F), PartPose.offsetAndRotation(0.0F, -13.0F, 3.0F, 0.1F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    private static LayerDefinition archmage_veyl() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(4, 0).addBox(-4.0F, -12.0F, -2.5F, 8.0F, 12.0F, 5.0F).texOffs(78, 30).addBox(-5.0F, -12.5F, -3.0F, 10.0F, 4.0F, 6.0F).texOffs(40, 44).addBox(-4.5F, -3.0F, -3.0F, 9.0F, 2.0F, 6.0F).texOffs(90, 44).addBox(-4.0F, -15.0F, 0.5F, 8.0F, 4.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -16.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(96, 0).addBox(-3.5F, -8.0F, -3.5F, 7.0F, 8.0F, 7.0F).texOffs(70, 44).addBox(-2.5F, -10.0F, -1.5F, 5.0F, 2.0F, 5.0F).texOffs(118, 44).addBox(-1.0F, -11.0F, 1.5F, 2.0F, 2.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -12.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_halo = p_head.addOrReplaceChild("halo", CubeListBuilder.create().texOffs(30, 0).addBox(-8.0F, -8.0F, 0.0F, 16.0F, 16.0F, 0.0F), PartPose.offsetAndRotation(0.0F, -4.5F, 5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 30).addBox(-1.0F, -1.5F, -2.0F, 4.0F, 10.0F, 4.0F).texOffs(0, 44).addBox(-1.5F, 6.0F, -2.5F, 5.0F, 4.0F, 5.0F).texOffs(0, 53).addBox(-0.5F, 10.0F, -1.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(5.0F, -10.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(16, 30).addBox(-3.0F, -1.5F, -2.0F, 4.0F, 10.0F, 4.0F).texOffs(20, 44).addBox(-3.5F, 6.0F, -2.5F, 5.0F, 4.0F, 5.0F).texOffs(8, 53).addBox(-1.5F, 10.0F, -1.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(-5.0F, -10.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_staff = p_right_arm.addOrReplaceChild("staff", CubeListBuilder.create().texOffs(0, 0).addBox(-0.5F, -17.0F, -0.5F, 1.0F, 29.0F, 1.0F).texOffs(16, 53).addBox(-1.5F, -19.0F, -0.5F, 1.0F, 3.0F, 1.0F).texOffs(20, 53).addBox(0.5F, -19.0F, -0.5F, 1.0F, 3.0F, 1.0F).texOffs(24, 53).addBox(-0.5F, -19.0F, -1.5F, 1.0F, 3.0F, 1.0F).texOffs(28, 53).addBox(-0.5F, -19.0F, 0.5F, 1.0F, 3.0F, 1.0F).texOffs(110, 44).addBox(-1.0F, -23.0F, -1.0F, 2.0F, 4.0F, 2.0F), PartPose.offsetAndRotation(-1.0F, 11.0F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_skirt = p_body.addOrReplaceChild("skirt", CubeListBuilder.create().texOffs(48, 30).addBox(-4.5F, 0.0F, -3.0F, 9.0F, 7.0F, 6.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_skirt2 = p_skirt.addOrReplaceChild("skirt2", CubeListBuilder.create().texOffs(62, 0).addBox(-5.0F, 0.0F, -3.5F, 10.0F, 8.0F, 7.0F), PartPose.offsetAndRotation(0.0F, 7.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_body.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(32, 30).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F), PartPose.offsetAndRotation(2.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_body.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(40, 30).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F), PartPose.offsetAndRotation(-2.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    private static LayerDefinition hrodgar() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(228, 0).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 10.0F, 3.0F).texOffs(188, 0).addBox(-2.5F, 9.0F, -2.5F, 5.0F, 9.0F, 5.0F).texOffs(86, 43).addBox(-2.5F, 16.0F, -4.0F, 5.0F, 2.0F, 2.0F).texOffs(134, 43).addBox(-2.0F, 8.0F, -2.6F, 4.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(3.5F, -18.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(240, 0).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 10.0F, 3.0F).texOffs(208, 0).addBox(-2.5F, 9.0F, -2.5F, 5.0F, 9.0F, 5.0F).texOffs(100, 43).addBox(-2.5F, 16.0F, -4.0F, 5.0F, 2.0F, 2.0F).texOffs(144, 43).addBox(-2.0F, 8.0F, -2.6F, 4.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(-3.5F, -18.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(122, 30).addBox(-5.0F, -2.0F, -3.0F, 10.0F, 4.0F, 6.0F).texOffs(0, 30).addBox(-1.5F, -12.0F, 0.0F, 3.0F, 10.0F, 3.0F).texOffs(52, 0).addBox(-6.0F, -16.0F, -4.0F, 12.0F, 10.0F, 8.0F).texOffs(154, 30).addBox(-2.5F, -13.0F, -2.0F, 5.0F, 5.0F, 5.0F).texOffs(16, 43).addBox(-5.5F, -3.0F, -3.5F, 11.0F, 2.0F, 7.0F).texOffs(0, 43).addBox(-4.0F, -1.0F, -4.0F, 8.0F, 10.0F, 0.0F).texOffs(12, 30).addBox(-7.0F, -17.5F, -4.5F, 14.0F, 3.0F, 9.0F), PartPose.offsetAndRotation(0.0F, -18.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(92, 0).addBox(-4.5F, -9.0F, -4.5F, 9.0F, 9.0F, 9.0F).texOffs(56, 43).addBox(-3.5F, -1.0F, -4.5F, 7.0F, 2.0F, 6.0F).texOffs(58, 30).addBox(-5.0F, -10.0F, -5.0F, 10.0F, 2.0F, 10.0F).texOffs(126, 43).addBox(-5.0F, -13.0F, -5.0F, 1.0F, 3.0F, 1.0F).texOffs(82, 43).addBox(-0.5F, -14.0F, -5.0F, 1.0F, 4.0F, 1.0F).texOffs(130, 43).addBox(4.0F, -13.0F, -5.0F, 1.0F, 3.0F, 1.0F).texOffs(180, 43).addBox(-5.0F, -12.0F, 4.0F, 1.0F, 2.0F, 1.0F).texOffs(184, 43).addBox(4.0F, -12.0F, 4.0F, 1.0F, 2.0F, 1.0F).texOffs(162, 43).addBox(-1.0F, -12.0F, -5.4F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -17.5F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(128, 0).addBox(-2.5F, -3.0F, -4.0F, 7.0F, 6.0F, 8.0F).texOffs(28, 0).addBox(-0.5F, 0.0F, -1.5F, 3.0F, 18.0F, 3.0F).texOffs(174, 30).addBox(-1.5F, 8.0F, -2.5F, 5.0F, 5.0F, 5.0F).texOffs(194, 30).addBox(-1.5F, 15.0F, -2.5F, 5.0F, 5.0F, 5.0F), PartPose.offsetAndRotation(8.5F, -15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(158, 0).addBox(-4.5F, -3.0F, -4.0F, 7.0F, 6.0F, 8.0F).texOffs(40, 0).addBox(-2.5F, 0.0F, -1.5F, 3.0F, 18.0F, 3.0F).texOffs(214, 30).addBox(-3.5F, 8.0F, -2.5F, 5.0F, 5.0F, 5.0F).texOffs(234, 30).addBox(-3.5F, 15.0F, -2.5F, 5.0F, 5.0F, 5.0F), PartPose.offsetAndRotation(-8.5F, -15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_flail_chain = p_right_arm.addOrReplaceChild("flail_chain", CubeListBuilder.create().texOffs(52, 43).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 8.0F, 1.0F), PartPose.offsetAndRotation(-1.0F, 19.0F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_flail_head = p_flail_chain.addOrReplaceChild("flail_head", CubeListBuilder.create().texOffs(98, 30).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 6.0F, 6.0F).texOffs(114, 43).addBox(-4.0F, 2.0F, -1.0F, 1.0F, 2.0F, 2.0F).texOffs(120, 43).addBox(3.0F, 2.0F, -1.0F, 1.0F, 2.0F, 2.0F).texOffs(154, 43).addBox(-1.0F, 6.0F, -1.0F, 2.0F, 1.0F, 2.0F).texOffs(168, 43).addBox(-1.0F, 2.0F, -4.0F, 2.0F, 2.0F, 1.0F).texOffs(174, 43).addBox(-1.0F, 2.0F, 3.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_cape = p_body.addOrReplaceChild("cape", CubeListBuilder.create().texOffs(0, 0).addBox(-7.0F, 0.0F, 0.0F, 14.0F, 30.0F, 0.0F), PartPose.offsetAndRotation(0.0F, -17.0F, 4.5F, 0.1F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 256, 64);
    }

    private static LayerDefinition morvane() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(112, 0).addBox(-2.5F, 0.0F, -2.5F, 5.0F, 15.0F, 5.0F).texOffs(176, 42).addBox(-3.0F, 6.0F, -3.0F, 6.0F, 2.0F, 1.0F).texOffs(198, 28).addBox(-3.0F, 13.0F, -4.0F, 6.0F, 2.0F, 7.0F), PartPose.offsetAndRotation(3.0F, -15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(132, 0).addBox(-2.5F, 0.0F, -2.5F, 5.0F, 15.0F, 5.0F).texOffs(190, 42).addBox(-3.0F, 6.0F, -3.0F, 6.0F, 2.0F, 1.0F).texOffs(224, 28).addBox(-3.0F, 13.0F, -4.0F, 6.0F, 2.0F, 7.0F), PartPose.offsetAndRotation(-3.0F, -15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(74, 0).addBox(-6.0F, -14.0F, -3.5F, 12.0F, 14.0F, 7.0F).texOffs(76, 28).addBox(-5.5F, -3.0F, -4.0F, 11.0F, 3.0F, 8.0F).texOffs(48, 42).addBox(-5.0F, 0.0F, -4.0F, 10.0F, 6.0F, 1.0F).texOffs(70, 42).addBox(-5.0F, 0.0F, 3.0F, 10.0F, 6.0F, 1.0F).texOffs(18, 42).addBox(-4.5F, -15.5F, -3.0F, 9.0F, 2.0F, 6.0F).texOffs(118, 42).addBox(-3.0F, -12.0F, 3.5F, 2.0F, 3.0F, 2.0F).texOffs(126, 42).addBox(1.0F, -12.0F, 3.5F, 2.0F, 3.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(192, 0).addBox(-4.0F, -9.0F, -4.0F, 8.0F, 9.0F, 8.0F).texOffs(30, 28).addBox(-4.5F, -3.0F, -4.5F, 9.0F, 3.0F, 9.0F).texOffs(92, 42).addBox(-5.0F, -8.0F, -1.0F, 1.0F, 3.0F, 3.0F).texOffs(100, 42).addBox(4.0F, -8.0F, -1.0F, 1.0F, 3.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_crown = p_head.addOrReplaceChild("crown", CubeListBuilder.create().texOffs(114, 28).addBox(-4.5F, -1.0F, -4.5F, 9.0F, 2.0F, 9.0F).texOffs(160, 42).addBox(-4.5F, -4.0F, -4.5F, 1.0F, 3.0F, 1.0F).texOffs(150, 42).addBox(-0.5F, -5.0F, -4.5F, 1.0F, 4.0F, 1.0F).texOffs(164, 42).addBox(3.5F, -4.0F, -4.5F, 1.0F, 3.0F, 1.0F).texOffs(168, 42).addBox(-4.5F, -4.0F, 3.5F, 1.0F, 3.0F, 1.0F).texOffs(172, 42).addBox(3.5F, -4.0F, 3.5F, 1.0F, 3.0F, 1.0F).texOffs(210, 42).addBox(-4.5F, -3.0F, -0.5F, 1.0F, 2.0F, 1.0F).texOffs(214, 42).addBox(3.5F, -3.0F, -0.5F, 1.0F, 2.0F, 1.0F).texOffs(218, 42).addBox(-0.5F, -3.0F, 3.5F, 1.0F, 2.0F, 1.0F).texOffs(204, 42).addBox(-1.0F, -1.5F, -5.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -10.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(224, 0).addBox(-2.5F, -3.5F, -4.0F, 7.0F, 6.0F, 8.0F).texOffs(134, 42).addBox(0.0F, -6.0F, -1.0F, 2.0F, 3.0F, 2.0F).texOffs(152, 0).addBox(-1.5F, -1.0F, -2.5F, 5.0F, 13.0F, 5.0F).texOffs(150, 28).addBox(-2.0F, 9.0F, -3.0F, 6.0F, 5.0F, 6.0F), PartPose.offsetAndRotation(8.0F, -12.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(0, 28).addBox(-4.5F, -3.5F, -4.0F, 7.0F, 6.0F, 8.0F).texOffs(142, 42).addBox(-2.0F, -6.0F, -1.0F, 2.0F, 3.0F, 2.0F).texOffs(172, 0).addBox(-3.5F, -1.0F, -2.5F, 5.0F, 13.0F, 5.0F).texOffs(174, 28).addBox(-4.0F, 9.0F, -3.0F, 6.0F, 5.0F, 6.0F), PartPose.offsetAndRotation(-8.0F, -12.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_sword = p_right_arm.addOrReplaceChild("sword", CubeListBuilder.create().texOffs(108, 42).addBox(-1.5F, -1.5F, 3.0F, 3.0F, 3.0F, 2.0F).texOffs(0, 42).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 7.0F).texOffs(66, 28).addBox(-1.5F, -5.0F, -6.0F, 3.0F, 10.0F, 2.0F).texOffs(0, 0).addBox(-0.5F, -2.0F, -30.0F, 1.0F, 4.0F, 24.0F).texOffs(154, 42).addBox(-0.5F, -1.0F, -32.0F, 1.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(-1.0F, 11.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_cape = p_body.addOrReplaceChild("cape", CubeListBuilder.create().texOffs(50, 0).addBox(-6.0F, 0.0F, 0.0F, 12.0F, 26.0F, 0.0F), PartPose.offsetAndRotation(0.0F, -14.0F, 3.5F, 0.15F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 256, 64);
    }

    private static LayerDefinition crown_blade() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_blade = p_hull.addOrReplaceChild("blade", CubeListBuilder.create().texOffs(0, 0).addBox(-1.0F, -6.0F, -0.5F, 2.0F, 14.0F, 1.0F).texOffs(34, 0).addBox(-0.5F, 8.0F, -0.5F, 1.0F, 2.0F, 1.0F).texOffs(10, 0).addBox(-3.0F, -7.0F, -1.0F, 6.0F, 1.0F, 2.0F).texOffs(6, 0).addBox(-0.5F, -11.0F, -0.5F, 1.0F, 4.0F, 1.0F).texOffs(26, 0).addBox(-1.0F, -12.0F, -1.0F, 2.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    private static LayerDefinition glimmerfawn() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0F, -3.0F, -7.0F, 6.0F, 6.0F, 13.0F).texOffs(24, 19).addBox(-2.5F, 2.5F, -6.0F, 5.0F, 1.0F, 10.0F), PartPose.offsetAndRotation(0.0F, -13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(38, 0).addBox(-1.5F, -8.0F, -2.0F, 3.0F, 9.0F, 3.0F).texOffs(0, 31).addBox(-2.0F, -11.0F, -4.0F, 4.0F, 4.0F, 5.0F).texOffs(26, 31).addBox(-1.0F, -9.5F, -7.0F, 2.0F, 2.0F, 3.0F).texOffs(18, 31).addBox(1.0F, -17.0F, -2.0F, 1.0F, 6.0F, 1.0F).texOffs(8, 40).addBox(1.0F, -17.0F, -2.0F, 3.0F, 1.0F, 1.0F).texOffs(44, 31).addBox(2.0F, -20.0F, -2.0F, 1.0F, 3.0F, 1.0F).texOffs(22, 31).addBox(-2.0F, -17.0F, -2.0F, 1.0F, 6.0F, 1.0F).texOffs(16, 40).addBox(-4.0F, -17.0F, -2.0F, 3.0F, 1.0F, 1.0F).texOffs(48, 31).addBox(-3.0F, -20.0F, -2.0F, 1.0F, 3.0F, 1.0F).texOffs(24, 40).addBox(3.5F, -18.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(28, 40).addBox(-4.5F, -18.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(32, 40).addBox(2.0F, -21.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(36, 40).addBox(-3.0F, -21.0F, -2.0F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -2.0F, -6.0F, -0.2F, 0.0F, 0.0F));
        PartDefinition p_ear_l = p_head.addOrReplaceChild("ear_l", CubeListBuilder.create().texOffs(52, 31).addBox(0.0F, -1.0F, -0.5F, 3.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(2.0F, -10.0F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_ear_r = p_head.addOrReplaceChild("ear_r", CubeListBuilder.create().texOffs(0, 40).addBox(-3.0F, -1.0F, -0.5F, 3.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(-2.0F, -10.0F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fl = p_body.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(50, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(2.0F, 3.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fr = p_body.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(0, 19).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(-2.0F, 3.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_bl = p_body.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(8, 19).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(2.0F, 3.0F, 4.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_br = p_body.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(16, 19).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(-2.0F, 3.0F, 4.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(36, 31).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -2.5F, 6.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    private static LayerDefinition duskhare() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2.0F, -2.0F, -3.0F, 4.0F, 4.0F, 6.0F), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(40, 0).addBox(-1.5F, -3.0F, -3.0F, 3.0F, 3.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -2.0F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_ear_l = p_head.addOrReplaceChild("ear_l", CubeListBuilder.create().texOffs(52, 0).addBox(-0.5F, -5.0F, -0.5F, 1.0F, 5.0F, 1.0F), PartPose.offsetAndRotation(0.8F, -3.0F, -1.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_ear_r = p_head.addOrReplaceChild("ear_r", CubeListBuilder.create().texOffs(56, 0).addBox(-0.5F, -5.0F, -0.5F, 1.0F, 5.0F, 1.0F), PartPose.offsetAndRotation(-0.8F, -3.0F, -1.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fl = p_body.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(60, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F), PartPose.offsetAndRotation(1.0F, 1.0F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fr = p_body.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(0, 10).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 3.0F, 1.0F), PartPose.offsetAndRotation(-1.0F, 1.0F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_bl = p_body.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(20, 0).addBox(-1.0F, 0.0F, -1.5F, 2.0F, 4.0F, 3.0F), PartPose.offsetAndRotation(1.3F, 0.0F, 2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_br = p_body.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(30, 0).addBox(-1.0F, 0.0F, -1.5F, 2.0F, 4.0F, 3.0F), PartPose.offsetAndRotation(-1.3F, 0.0F, 2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(4, 10).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -1.0F, 3.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    private static LayerDefinition mossback_tortoise() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 16).addBox(-5.0F, -4.0F, -6.0F, 10.0F, 4.0F, 12.0F).texOffs(0, 0).addBox(-6.0F, 0.0F, -7.0F, 12.0F, 2.0F, 14.0F).texOffs(0, 32).addBox(-4.0F, -6.0F, -4.0F, 8.0F, 2.0F, 8.0F).texOffs(36, 42).addBox(-2.0F, -7.0F, -2.0F, 4.0F, 1.0F, 4.0F), PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(32, 32).addBox(-1.5F, -1.5F, -4.0F, 3.0F, 3.0F, 4.0F), PartPose.offsetAndRotation(0.0F, 0.5F, -7.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fl = p_body.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(46, 32).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 4.0F, 3.0F), PartPose.offsetAndRotation(4.0F, 1.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fr = p_body.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(0, 42).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 4.0F, 3.0F), PartPose.offsetAndRotation(-4.0F, 1.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_bl = p_body.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(12, 42).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 4.0F, 3.0F), PartPose.offsetAndRotation(4.0F, 1.0F, 5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_br = p_body.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(24, 42).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 4.0F, 3.0F), PartPose.offsetAndRotation(-4.0F, 1.0F, 5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(52, 42).addBox(-0.5F, -0.5F, 0.0F, 1.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 1.0F, 7.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    private static LayerDefinition lumen_beetle() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-1.5F, -1.0F, -2.0F, 3.0F, 2.0F, 4.0F).texOffs(14, 0).addBox(-1.0F, -0.8F, 2.0F, 2.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(22, 0).addBox(-1.0F, -0.5F, -1.5F, 2.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 0.0F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_0 = p_body.addOrReplaceChild("leg_0", CubeListBuilder.create().texOffs(28, 0).addBox(0.0F, -0.45F, -0.45F, 2.0F, 0.0F, 0.0F), PartPose.offsetAndRotation(1.5F, 0.5F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_1 = p_body.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(32, 0).addBox(-2.5F, -0.45F, -0.45F, 2.0F, 0.0F, 0.0F), PartPose.offsetAndRotation(-1.5F, 0.5F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_2 = p_body.addOrReplaceChild("leg_2", CubeListBuilder.create().texOffs(36, 0).addBox(0.0F, -0.45F, -0.45F, 2.0F, 0.0F, 0.0F), PartPose.offsetAndRotation(1.5F, 0.5F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_3 = p_body.addOrReplaceChild("leg_3", CubeListBuilder.create().texOffs(40, 0).addBox(-2.5F, -0.45F, -0.45F, 2.0F, 0.0F, 0.0F), PartPose.offsetAndRotation(-1.5F, 0.5F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_4 = p_body.addOrReplaceChild("leg_4", CubeListBuilder.create().texOffs(44, 0).addBox(0.0F, -0.45F, -0.45F, 2.0F, 0.0F, 0.0F), PartPose.offsetAndRotation(1.5F, 0.5F, 2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_5 = p_body.addOrReplaceChild("leg_5", CubeListBuilder.create().texOffs(48, 0).addBox(-2.5F, -0.45F, -0.45F, 2.0F, 0.0F, 0.0F), PartPose.offsetAndRotation(-1.5F, 0.5F, 2.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    private static LayerDefinition tidewader() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2.0F, -2.0F, -4.0F, 4.0F, 4.0F, 7.0F), PartPose.offsetAndRotation(0.0F, -11.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_neck = p_body.addOrReplaceChild("neck", CubeListBuilder.create().texOffs(0, 11).addBox(-0.75F, -7.0F, -0.75F, 1.0F, 7.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -1.0F, -3.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_neck.addOrReplaceChild("head", CubeListBuilder.create().texOffs(4, 11).addBox(-1.0F, -2.0F, -1.5F, 2.0F, 2.0F, 3.0F).texOffs(14, 11).addBox(-0.5F, -1.5F, -5.5F, 1.0F, 1.0F, 4.0F).texOffs(56, 11).addBox(-0.25F, -3.0F, 0.5F, 0.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -7.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_wing = p_body.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(22, 0).addBox(0.0F, 0.0F, 0.0F, 1.0F, 3.0F, 7.0F), PartPose.offsetAndRotation(2.0F, -1.5F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_wing = p_body.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(38, 0).addBox(-1.0F, 0.0F, 0.0F, 1.0F, 3.0F, 7.0F), PartPose.offsetAndRotation(-2.0F, -1.5F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_body.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(54, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F).texOffs(36, 11).addBox(-1.0F, 8.5F, -2.0F, 2.0F, 0.0F, 3.0F), PartPose.offsetAndRotation(1.0F, 2.0F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_body.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(58, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 9.0F, 1.0F).texOffs(46, 11).addBox(-1.0F, 8.5F, -2.0F, 2.0F, 0.0F, 3.0F), PartPose.offsetAndRotation(-1.0F, 2.0F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(24, 11).addBox(-1.5F, 0.0F, 0.0F, 3.0F, 1.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -1.0F, 3.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    private static LayerDefinition thornback_boar() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -4.0F, -7.0F, 8.0F, 8.0F, 14.0F).texOffs(0, 22).addBox(-1.0F, -6.0F, -6.0F, 2.0F, 2.0F, 11.0F).texOffs(0, 35).addBox(-2.0F, -5.5F, -5.0F, 1.0F, 1.0F, 8.0F).texOffs(18, 35).addBox(1.0F, -5.5F, -5.0F, 1.0F, 1.0F, 8.0F), PartPose.offsetAndRotation(0.0F, -10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(26, 22).addBox(-3.5F, -3.0F, -6.0F, 7.0F, 6.0F, 6.0F).texOffs(24, 44).addBox(-2.0F, 0.0F, -8.0F, 4.0F, 3.0F, 2.0F).texOffs(36, 44).addBox(-3.0F, 0.5F, -8.0F, 1.0F, 3.0F, 1.0F).texOffs(40, 44).addBox(2.0F, 0.5F, -8.0F, 1.0F, 3.0F, 1.0F).texOffs(60, 44).addBox(-3.0F, -1.5F, -8.5F, 1.0F, 1.0F, 1.0F).texOffs(0, 53).addBox(2.0F, -1.5F, -8.5F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -1.0F, -7.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_ear_l = p_head.addOrReplaceChild("ear_l", CubeListBuilder.create().texOffs(48, 44).addBox(0.0F, -2.0F, 0.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(2.5F, -3.0F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_ear_r = p_head.addOrReplaceChild("ear_r", CubeListBuilder.create().texOffs(54, 44).addBox(-2.0F, -2.0F, 0.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(-2.5F, -3.0F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fl = p_body.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(36, 35).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 6.0F, 3.0F), PartPose.offsetAndRotation(2.5F, 4.0F, -4.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fr = p_body.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(48, 35).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 6.0F, 3.0F), PartPose.offsetAndRotation(-2.5F, 4.0F, -4.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_bl = p_body.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(0, 44).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 6.0F, 3.0F), PartPose.offsetAndRotation(2.5F, 4.0F, 4.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_br = p_body.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(12, 44).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 6.0F, 3.0F), PartPose.offsetAndRotation(-2.5F, 4.0F, 4.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(44, 44).addBox(-0.5F, 0.0F, 0.0F, 1.0F, 3.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -2.0F, 7.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    private static LayerDefinition stonewarden() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(84, 0).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 12.0F, 6.0F), PartPose.offsetAndRotation(3.5F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(0, 23).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 12.0F, 6.0F), PartPose.offsetAndRotation(-3.5F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(40, 0).addBox(-7.0F, -14.0F, -4.0F, 14.0F, 14.0F, 8.0F).texOffs(80, 41).addBox(-3.0F, -11.0F, -4.5F, 6.0F, 6.0F, 1.0F).texOffs(52, 23).addBox(-7.5F, -15.0F, -4.5F, 15.0F, 2.0F, 9.0F), PartPose.offsetAndRotation(0.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(24, 23).addBox(-3.5F, -7.0F, -3.5F, 7.0F, 7.0F, 7.0F).texOffs(0, 41).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 2.0F, 8.0F), PartPose.offsetAndRotation(0.0F, -14.0F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 0).addBox(-2.5F, -1.0F, -2.5F, 5.0F, 18.0F, 5.0F).texOffs(32, 41).addBox(-3.0F, 13.0F, -3.0F, 6.0F, 4.0F, 6.0F), PartPose.offsetAndRotation(9.5F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(20, 0).addBox(-2.5F, -1.0F, -2.5F, 5.0F, 18.0F, 5.0F).texOffs(56, 41).addBox(-3.0F, 13.0F, -3.0F, 6.0F, 4.0F, 6.0F), PartPose.offsetAndRotation(-9.5F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    private static LayerDefinition runewisp() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2.0F, -2.0F, -2.0F, 4.0F, 4.0F, 4.0F).texOffs(32, 0).addBox(-1.0F, -3.0F, -1.0F, 2.0F, 6.0F, 2.0F).texOffs(40, 0).addBox(-3.0F, -1.0F, -1.0F, 6.0F, 2.0F, 2.0F).texOffs(16, 0).addBox(-1.0F, -1.0F, -3.0F, 2.0F, 2.0F, 6.0F), PartPose.offsetAndRotation(0.0F, -10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_orbit_0 = p_body.addOrReplaceChild("orbit_0", CubeListBuilder.create().texOffs(56, 0).addBox(4.0F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F).texOffs(60, 0).addBox(1.75F, -0.5F, 3.397F, 1.0F, 1.0F, 1.0F).texOffs(0, 8).addBox(-2.75F, -0.5F, 3.397F, 1.0F, 1.0F, 1.0F).texOffs(4, 8).addBox(-5.0F, -0.5F, -0.5F, 1.0F, 1.0F, 1.0F).texOffs(8, 8).addBox(-2.75F, -0.5F, -4.397F, 1.0F, 1.0F, 1.0F).texOffs(12, 8).addBox(1.75F, -0.5F, -4.397F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_orbit_1 = p_body.addOrReplaceChild("orbit_1", CubeListBuilder.create().texOffs(32, 8).addBox(5.6F, -0.4F, -0.4F, 0.0F, 0.0F, 0.0F).texOffs(33, 8).addBox(3.843F, -0.4F, 3.843F, 0.0F, 0.0F, 0.0F).texOffs(34, 8).addBox(-0.4F, -0.4F, 5.6F, 0.0F, 0.0F, 0.0F).texOffs(35, 8).addBox(-4.643F, -0.4F, 3.843F, 0.0F, 0.0F, 0.0F).texOffs(36, 8).addBox(-6.4F, -0.4F, -0.4F, 0.0F, 0.0F, 0.0F).texOffs(37, 8).addBox(-4.643F, -0.4F, -4.643F, 0.0F, 0.0F, 0.0F).texOffs(38, 8).addBox(-0.4F, -0.4F, -6.4F, 0.0F, 0.0F, 0.0F).texOffs(39, 8).addBox(3.843F, -0.4F, -4.643F, 0.0F, 0.0F, 0.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_orbit_2 = p_body.addOrReplaceChild("orbit_2", CubeListBuilder.create().texOffs(16, 8).addBox(2.4F, -0.6F, -0.6F, 1.0F, 1.0F, 1.0F).texOffs(20, 8).addBox(-0.6F, -0.6F, 2.4F, 1.0F, 1.0F, 1.0F).texOffs(24, 8).addBox(-3.6F, -0.6F, -0.6F, 1.0F, 1.0F, 1.0F).texOffs(28, 8).addBox(-0.6F, -0.6F, -3.6F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    private static LayerDefinition drowned_choirmonk() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(24, 17).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(1.9F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(40, 17).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(-1.9F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 17).addBox(-4.0F, 0.0F, -2.0F, 8.0F, 12.0F, 4.0F).texOffs(30, 33).addBox(-3.0F, 2.0F, 2.05F, 1.0F, 9.0F, 0.0F).texOffs(28, 33).addBox(1.0F, 1.0F, 2.05F, 1.0F, 11.0F, 0.0F), PartPose.offsetAndRotation(0.0F, -24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(30, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F).texOffs(32, 33).addBox(-2.0F, -10.0F, -2.0F, 4.0F, 2.0F, 4.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 33).addBox(-1.0F, -2.0F, -2.0F, 3.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(5.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(14, 33).addBox(-2.0F, -2.0F, -2.0F, 3.0F, 12.0F, 4.0F).texOffs(48, 33).addBox(-1.5F, 9.0F, -5.0F, 2.0F, 4.0F, 2.0F).texOffs(56, 33).addBox(-1.0F, 7.0F, -4.5F, 1.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(-5.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_robe = p_body.addOrReplaceChild("robe", CubeListBuilder.create().texOffs(0, 0).addBox(-4.5F, 0.0F, -3.0F, 9.0F, 11.0F, 6.0F), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    private static LayerDefinition mire_hag() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(0, 23).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(1.9F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(16, 23).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(-1.9F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(34, 0).addBox(-4.0F, 0.0F, -2.0F, 8.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(0.0F, -24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 39).addBox(-3.5F, -7.0F, -3.5F, 7.0F, 7.0F, 7.0F).texOffs(28, 39).addBox(-4.0F, -8.0F, -3.0F, 8.0F, 6.0F, 7.0F).texOffs(12, 53).addBox(-1.0F, -4.0F, -6.0F, 2.0F, 3.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(32, 23).addBox(-1.0F, -2.0F, -2.0F, 3.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(5.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(46, 23).addBox(-2.0F, -2.0F, -2.0F, 3.0F, 12.0F, 4.0F).texOffs(0, 0).addBox(-1.0F, -8.0F, -3.0F, 1.0F, 22.0F, 1.0F).texOffs(0, 53).addBox(-2.0F, -11.0F, -4.0F, 3.0F, 3.0F, 3.0F), PartPose.offsetAndRotation(-5.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_robe = p_body.addOrReplaceChild("robe", CubeListBuilder.create().texOffs(4, 0).addBox(-4.5F, 0.0F, -3.0F, 9.0F, 11.0F, 6.0F), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    private static LayerDefinition grave_crawler() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0F, -2.0F, -5.0F, 6.0F, 4.0F, 10.0F).texOffs(52, 0).addBox(-1.0F, -1.5F, 5.0F, 2.0F, 2.0F, 4.0F), PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(32, 0).addBox(-2.5F, -2.5F, -5.0F, 5.0F, 5.0F, 5.0F), PartPose.offsetAndRotation(0.0F, -1.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_0 = p_body.addOrReplaceChild("leg_0", CubeListBuilder.create().texOffs(0, 14).addBox(0.0F, -0.5F, -0.5F, 6.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(3.0F, 0.0F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_1 = p_body.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(14, 14).addBox(-6.0F, -0.5F, -0.5F, 6.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-3.0F, 0.0F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_2 = p_body.addOrReplaceChild("leg_2", CubeListBuilder.create().texOffs(28, 14).addBox(0.0F, -0.5F, -0.5F, 6.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(3.0F, 0.0F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_3 = p_body.addOrReplaceChild("leg_3", CubeListBuilder.create().texOffs(42, 14).addBox(-6.0F, -0.5F, -0.5F, 6.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-3.0F, 0.0F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_4 = p_body.addOrReplaceChild("leg_4", CubeListBuilder.create().texOffs(0, 16).addBox(0.0F, -0.5F, -0.5F, 6.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(3.0F, 0.0F, 3.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_5 = p_body.addOrReplaceChild("leg_5", CubeListBuilder.create().texOffs(14, 16).addBox(-6.0F, -0.5F, -0.5F, 6.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-3.0F, 0.0F, 3.5F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    private static LayerDefinition gloam_stalker() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.0F, -3.0F, -7.0F, 6.0F, 5.0F, 14.0F).texOffs(40, 0).addBox(-0.5F, -4.0F, -5.0F, 1.0F, 1.0F, 10.0F), PartPose.offsetAndRotation(0.0F, -9.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(22, 19).addBox(-2.5F, -2.5F, -5.0F, 5.0F, 5.0F, 5.0F), PartPose.offsetAndRotation(0.0F, -1.0F, -7.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_ear_l = p_head.addOrReplaceChild("ear_l", CubeListBuilder.create().texOffs(8, 39).addBox(0.0F, -2.5F, 0.0F, 1.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(1.5F, -2.5F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_ear_r = p_head.addOrReplaceChild("ear_r", CubeListBuilder.create().texOffs(12, 39).addBox(-1.0F, -2.5F, 0.0F, 1.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(-1.5F, -2.5F, -2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_jaw = p_head.addOrReplaceChild("jaw", CubeListBuilder.create().texOffs(24, 30).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 1.5F, -3.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fl = p_body.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(42, 19).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 7.0F, 2.0F).texOffs(34, 30).addBox(-1.0F, 6.0F, -1.5F, 2.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(2.0F, 2.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fr = p_body.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(50, 19).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 7.0F, 2.0F).texOffs(42, 30).addBox(-1.0F, 6.0F, -1.5F, 2.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(-2.0F, 2.0F, -5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_bl = p_body.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(0, 30).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 7.0F, 2.0F).texOffs(50, 30).addBox(-1.0F, 6.0F, -1.5F, 2.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(2.0F, 2.0F, 5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_br = p_body.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(8, 30).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 7.0F, 2.0F).texOffs(0, 39).addBox(-1.0F, 6.0F, -1.5F, 2.0F, 1.0F, 2.0F), PartPose.offsetAndRotation(-2.0F, 2.0F, 5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(0, 19).addBox(-0.5F, -0.5F, 0.0F, 1.0F, 1.0F, 10.0F).texOffs(16, 30).addBox(-1.0F, -1.0F, 10.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, -2.0F, 7.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    private static LayerDefinition shade_wraith() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(30, 0).addBox(-4.0F, -2.0F, -2.5F, 8.0F, 10.0F, 5.0F), PartPose.offsetAndRotation(0.0F, -20.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 17).addBox(-3.5F, -7.0F, -3.5F, 7.0F, 7.0F, 7.0F).texOffs(44, 17).addBox(-2.5F, -9.0F, -1.0F, 5.0F, 2.0F, 5.0F), PartPose.offsetAndRotation(0.0F, -2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_cloak = p_body.addOrReplaceChild("cloak", CubeListBuilder.create().texOffs(0, 0).addBox(-4.5F, 0.0F, -3.0F, 9.0F, 11.0F, 6.0F), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(28, 17).addBox(0.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F).texOffs(0, 31).addBox(-0.5F, 11.0F, -1.5F, 3.0F, 3.0F, 3.0F), PartPose.offsetAndRotation(4.5F, -1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(36, 17).addBox(-2.0F, 0.0F, -1.0F, 2.0F, 12.0F, 2.0F).texOffs(12, 31).addBox(-2.5F, 11.0F, -1.5F, 3.0F, 3.0F, 3.0F), PartPose.offsetAndRotation(-4.5F, -1.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    private static LayerDefinition lumenite_mite() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-2.0F, -1.5F, -2.5F, 4.0F, 3.0F, 5.0F).texOffs(28, 0).addBox(-1.0F, -3.5F, -1.0F, 2.0F, 2.0F, 2.0F).texOffs(36, 0).addBox(0.5F, -3.0F, 1.0F, 1.0F, 2.0F, 1.0F).texOffs(24, 8).addBox(-1.5F, -2.8F, -2.0F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -2.5F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(18, 0).addBox(-1.5F, -1.0F, -2.0F, 3.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 0.0F, -2.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_0 = p_body.addOrReplaceChild("leg_0", CubeListBuilder.create().texOffs(40, 0).addBox(0.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(2.0F, 1.0F, -1.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_1 = p_body.addOrReplaceChild("leg_1", CubeListBuilder.create().texOffs(48, 0).addBox(-3.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-2.0F, 1.0F, -1.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_2 = p_body.addOrReplaceChild("leg_2", CubeListBuilder.create().texOffs(56, 0).addBox(0.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(2.0F, 1.0F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_3 = p_body.addOrReplaceChild("leg_3", CubeListBuilder.create().texOffs(0, 8).addBox(-3.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-2.0F, 1.0F, 0.5F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_4 = p_body.addOrReplaceChild("leg_4", CubeListBuilder.create().texOffs(8, 8).addBox(0.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(2.0F, 1.0F, 2.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_5 = p_body.addOrReplaceChild("leg_5", CubeListBuilder.create().texOffs(16, 8).addBox(-3.0F, -0.5F, -0.5F, 3.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-2.0F, 1.0F, 2.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    private static LayerDefinition ashen_revenant() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(0, 16).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(1.9F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(16, 16).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(-1.9F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(32, 0).addBox(-4.0F, 0.0F, -2.0F, 8.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(0.0F, -24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F).texOffs(28, 32).addBox(-0.5F, -13.0F, -3.0F, 1.0F, 5.0F, 6.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(32, 16).addBox(-1.0F, -2.0F, -2.0F, 3.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(5.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(46, 16).addBox(-2.0F, -2.0F, -2.0F, 3.0F, 12.0F, 4.0F).texOffs(0, 32).addBox(-1.0F, 9.0F, -11.0F, 1.0F, 2.0F, 13.0F).texOffs(42, 32).addBox(-2.5F, 8.5F, -1.5F, 4.0F, 3.0F, 1.0F), PartPose.offsetAndRotation(-5.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    private static LayerDefinition elderhorn() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.5F, -3.5F, -8.0F, 7.0F, 7.0F, 15.0F).texOffs(22, 22).addBox(-3.0F, -5.0F, -8.0F, 6.0F, 3.0F, 6.0F).texOffs(92, 0).addBox(-3.6F, -2.0F, -3.0F, 0.0F, 3.0F, 8.0F).texOffs(108, 0).addBox(3.5F, -2.0F, -3.0F, 0.0F, 3.0F, 8.0F), PartPose.offsetAndRotation(0.0F, -13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(44, 0).addBox(-2.0F, -9.0F, -2.5F, 4.0F, 10.0F, 4.0F).texOffs(0, 22).addBox(-2.5F, -12.0F, -5.0F, 5.0F, 4.0F, 6.0F).texOffs(62, 22).addBox(-1.5F, -10.5F, -8.0F, 3.0F, 2.0F, 3.0F).texOffs(46, 22).addBox(1.5F, -19.0F, -2.0F, 1.0F, 8.0F, 1.0F).texOffs(0, 32).addBox(2.5F, -20.0F, -2.0F, 3.0F, 1.0F, 1.0F).texOffs(84, 22).addBox(3.5F, -23.0F, -2.0F, 1.0F, 4.0F, 1.0F).texOffs(16, 32).addBox(3.5F, -24.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(92, 22).addBox(5.5F, -22.0F, -2.0F, 1.0F, 3.0F, 1.0F).texOffs(20, 32).addBox(5.5F, -23.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(54, 22).addBox(7.5F, -24.0F, -2.0F, 1.0F, 5.0F, 1.0F).texOffs(24, 32).addBox(7.5F, -25.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(96, 22).addBox(4.5F, -26.0F, -2.0F, 1.0F, 3.0F, 1.0F).texOffs(28, 32).addBox(4.5F, -27.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(50, 22).addBox(-2.5F, -19.0F, -2.0F, 1.0F, 8.0F, 1.0F).texOffs(8, 32).addBox(-3.5F, -20.0F, -2.0F, 3.0F, 1.0F, 1.0F).texOffs(88, 22).addBox(-4.5F, -23.0F, -2.0F, 1.0F, 4.0F, 1.0F).texOffs(32, 32).addBox(-4.5F, -24.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(100, 22).addBox(-6.5F, -22.0F, -2.0F, 1.0F, 3.0F, 1.0F).texOffs(36, 32).addBox(-6.5F, -23.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(58, 22).addBox(-8.5F, -24.0F, -2.0F, 1.0F, 5.0F, 1.0F).texOffs(40, 32).addBox(-8.5F, -25.0F, -2.0F, 1.0F, 1.0F, 1.0F).texOffs(104, 22).addBox(-5.5F, -26.0F, -2.0F, 1.0F, 3.0F, 1.0F).texOffs(44, 32).addBox(-5.5F, -27.0F, -2.0F, 1.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -3.0F, -7.0F, -0.2F, 0.0F, 0.0F));
        PartDefinition p_ear_l = p_head.addOrReplaceChild("ear_l", CubeListBuilder.create().texOffs(108, 22).addBox(0.0F, -1.0F, -0.5F, 3.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(2.5F, -11.0F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_ear_r = p_head.addOrReplaceChild("ear_r", CubeListBuilder.create().texOffs(116, 22).addBox(-3.0F, -1.0F, -0.5F, 3.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(-2.5F, -11.0F, -1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fl = p_body.addOrReplaceChild("leg_fl", CubeListBuilder.create().texOffs(60, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(2.5F, 3.0F, -6.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_fr = p_body.addOrReplaceChild("leg_fr", CubeListBuilder.create().texOffs(68, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(-2.5F, 3.0F, -6.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_bl = p_body.addOrReplaceChild("leg_bl", CubeListBuilder.create().texOffs(76, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(2.5F, 3.0F, 5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg_br = p_body.addOrReplaceChild("leg_br", CubeListBuilder.create().texOffs(84, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(-2.5F, 3.0F, 5.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(74, 22).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -3.0F, 7.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    private static LayerDefinition bog_mother() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(0, 39).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(1.9F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(16, 39).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(-1.9F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(32, 23).addBox(-4.0F, 0.0F, -2.0F, 8.0F, 12.0F, 4.0F).texOffs(34, 55).addBox(-4.5F, -1.0F, -2.5F, 9.0F, 6.0F, 5.0F), PartPose.offsetAndRotation(0.0F, -24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 23).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F).texOffs(0, 55).addBox(-4.5F, -9.0F, -3.5F, 9.0F, 7.0F, 8.0F).texOffs(16, 70).addBox(-1.0F, -5.0F, -7.0F, 2.0F, 4.0F, 3.0F).texOffs(38, 70).addBox(-3.0F, -11.0F, -2.0F, 1.0F, 3.0F, 1.0F).texOffs(42, 70).addBox(2.0F, -11.0F, -2.0F, 1.0F, 3.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(32, 39).addBox(-1.0F, -2.0F, -2.0F, 3.0F, 12.0F, 4.0F).texOffs(26, 70).addBox(-0.5F, 10.0F, -1.5F, 3.0F, 3.0F, 3.0F), PartPose.offsetAndRotation(5.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(46, 39).addBox(-2.0F, -2.0F, -2.0F, 3.0F, 12.0F, 4.0F).texOffs(0, 0).addBox(-1.0F, -8.0F, -3.0F, 1.0F, 22.0F, 1.0F).texOffs(0, 70).addBox(-2.5F, -11.5F, -4.5F, 4.0F, 4.0F, 4.0F), PartPose.offsetAndRotation(-5.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_robe = p_body.addOrReplaceChild("robe", CubeListBuilder.create().texOffs(4, 0).addBox(-4.5F, 0.0F, -3.0F, 9.0F, 11.0F, 6.0F), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 128);
    }

    private static LayerDefinition cinder_colossus() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_hull = root.addOrReplaceChild("hull", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = p_hull.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(96, 0).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(1.9F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = p_hull.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(112, 0).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 12.0F, 4.0F), PartPose.offsetAndRotation(-1.9F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_body = p_hull.addOrReplaceChild("body", CubeListBuilder.create().texOffs(72, 0).addBox(-4.0F, 0.0F, -2.0F, 8.0F, 12.0F, 4.0F).texOffs(112, 21).addBox(-2.0F, 3.0F, -2.5F, 4.0F, 5.0F, 1.0F).texOffs(64, 21).addBox(-5.0F, -1.0F, -3.0F, 10.0F, 3.0F, 6.0F), PartPose.offsetAndRotation(0.0F, -24.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(40, 0).addBox(-4.0F, -8.0F, -4.0F, 8.0F, 8.0F, 8.0F).texOffs(96, 21).addBox(-5.0F, -10.0F, -1.0F, 2.0F, 5.0F, 2.0F).texOffs(104, 21).addBox(3.0F, -10.0F, -1.0F, 2.0F, 5.0F, 2.0F).texOffs(28, 21).addBox(-0.5F, -14.0F, -3.0F, 1.0F, 6.0F, 7.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 21).addBox(-1.0F, -2.0F, -2.0F, 3.0F, 12.0F, 4.0F).texOffs(44, 21).addBox(-0.5F, -3.0F, -3.0F, 4.0F, 4.0F, 6.0F), PartPose.offsetAndRotation(5.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(14, 21).addBox(-2.0F, -2.0F, -2.0F, 3.0F, 12.0F, 4.0F).texOffs(0, 0).addBox(-1.5F, 9.0F, -16.0F, 2.0F, 3.0F, 18.0F).texOffs(0, 37).addBox(-3.5F, 8.5F, -1.5F, 6.0F, 4.0F, 1.0F), PartPose.offsetAndRotation(-5.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }
}
