--[[ Rotstopper pistol: PG3D-inspired blocky sidearm, built from Parts and rigged for animation.
     Generated by tools/gen_rotstopper.py. Paste the whole file into the Studio command bar
     (View > Command Bar) and press Enter. A Tool named "Rotstopper" appears in PARENT.

     Rig: every animatable component has a Motor6D in the Handle named after the component
     (Slide, Barrel, Magazine, Trigger, Hammer, SlideStop). Frame and Grip are welded to the
     Handle; small detail parts are welded to their component, so they follow it.
]]

local PARENT = game:GetService("StarterPack")
local ADD_HAND_RIG_SCRIPT = true -- adds a Script that swaps RightGrip for a Motor6D on equip

-- name, component, size, CFrame (relative to Handle), colour, material
local PARTS = {
	{"Frame", "Frame", Vector3.new(0.28, 0.22, 1.3), CFrame.new(0, 0.39, -0.33, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#3B4048", "SmoothPlastic"},
	{"Beavertail", "Frame", Vector3.new(0.26, 0.12, 0.2), CFrame.new(0, 0.44, 0.42, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#3B4048", "SmoothPlastic"},
	{"RailLug1", "Frame", Vector3.new(0.2, 0.05, 0.08), CFrame.new(0, 0.255, -0.7, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"RailLug2", "Frame", Vector3.new(0.2, 0.05, 0.08), CFrame.new(0, 0.255, -0.82, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"RailLug3", "Frame", Vector3.new(0.2, 0.05, 0.08), CFrame.new(0, 0.255, -0.94, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"GuardFront", "Frame", Vector3.new(0.1, 0.26, 0.07), CFrame.new(0, 0.15, -0.6, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#3B4048", "SmoothPlastic"},
	{"GuardBottom", "Frame", Vector3.new(0.1, 0.07, 0.44), CFrame.new(0, 0.055, -0.39, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#3B4048", "SmoothPlastic"},
	{"TakedownPin", "Frame", Vector3.new(0.02, 0.06, 0.06), CFrame.new(0.145, 0.4, -0.55, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"Grip", "Grip", Vector3.new(0.3, 0.78, 0.4), CFrame.new(0, -0.03, 0.06, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#3B4048", "SmoothPlastic"},
	{"PanelL", "Grip", Vector3.new(0.025, 0.52, 0.3), CFrame.new(-0.16, -0.068812, 0.069677, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#6B7A3A", "SmoothPlastic"},
	{"EmblemL", "Grip", Vector3.new(0.012, 0.1, 0.1), CFrame.new(-0.178, 0.037921, 0.043065, 1, 0, 0, 0, 0.857167, -0.515038, 0, 0.515038, 0.857167), "#FF8C1A", "SmoothPlastic"},
	{"GrooveL1", "Grip", Vector3.new(0.012, 0.03, 0.26), CFrame.new(-0.178, -0.12703, 0.084192, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#4A5528", "SmoothPlastic"},
	{"GrooveL2", "Grip", Vector3.new(0.012, 0.03, 0.26), CFrame.new(-0.178, -0.204653, 0.103546, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#4A5528", "SmoothPlastic"},
	{"GrooveL3", "Grip", Vector3.new(0.012, 0.03, 0.26), CFrame.new(-0.178, -0.282277, 0.1229, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#4A5528", "SmoothPlastic"},
	{"PanelR", "Grip", Vector3.new(0.025, 0.52, 0.3), CFrame.new(0.16, -0.068812, 0.069677, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#6B7A3A", "SmoothPlastic"},
	{"EmblemR", "Grip", Vector3.new(0.012, 0.1, 0.1), CFrame.new(0.178, 0.037921, 0.043065, 1, 0, 0, 0, 0.857167, -0.515038, 0, 0.515038, 0.857167), "#FF8C1A", "SmoothPlastic"},
	{"GrooveR1", "Grip", Vector3.new(0.012, 0.03, 0.26), CFrame.new(0.178, -0.12703, 0.084192, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#4A5528", "SmoothPlastic"},
	{"GrooveR2", "Grip", Vector3.new(0.012, 0.03, 0.26), CFrame.new(0.178, -0.204653, 0.103546, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#4A5528", "SmoothPlastic"},
	{"GrooveR3", "Grip", Vector3.new(0.012, 0.03, 0.26), CFrame.new(0.178, -0.282277, 0.1229, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#4A5528", "SmoothPlastic"},
	{"FrontStrap1", "Grip", Vector3.new(0.26, 0.03, 0.02), CFrame.new(0, -0.118406, -0.129234, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#4A5528", "SmoothPlastic"},
	{"FrontStrap2", "Grip", Vector3.new(0.26, 0.03, 0.02), CFrame.new(0, -0.215435, -0.105042, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#4A5528", "SmoothPlastic"},
	{"FrontStrap3", "Grip", Vector3.new(0.26, 0.03, 0.02), CFrame.new(0, -0.312465, -0.080849, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#4A5528", "SmoothPlastic"},
	{"Slide", "Slide", Vector3.new(0.32, 0.3, 1.44), CFrame.new(0, 0.65, -0.36, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#A9B4C2", "SmoothPlastic"},
	{"Nose", "Slide", Vector3.new(0.28, 0.24, 0.1), CFrame.new(0, 0.64, -1.13, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#A9B4C2", "SmoothPlastic"},
	{"Rib", "Slide", Vector3.new(0.14, 0.04, 1.2), CFrame.new(0, 0.82, -0.42, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"Serration1", "Slide", Vector3.new(0.34, 0.2, 0.035), CFrame.new(0, 0.65, 0.28, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"Serration2", "Slide", Vector3.new(0.34, 0.2, 0.035), CFrame.new(0, 0.65, 0.2, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"Serration3", "Slide", Vector3.new(0.34, 0.2, 0.035), CFrame.new(0, 0.65, 0.12, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"Serration4", "Slide", Vector3.new(0.34, 0.2, 0.035), CFrame.new(0, 0.65, 0.04, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"Stripe", "Slide", Vector3.new(0.34, 0.05, 0.62), CFrame.new(0, 0.58, -0.62, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#FF8C1A", "SmoothPlastic"},
	{"EjectionPort", "Slide", Vector3.new(0.02, 0.12, 0.3), CFrame.new(0.165, 0.71, -0.12, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#16181C", "SmoothPlastic"},
	{"RearSightL", "Slide", Vector3.new(0.08, 0.09, 0.07), CFrame.new(-0.09, 0.845, 0.3, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#16181C", "SmoothPlastic"},
	{"RearSightR", "Slide", Vector3.new(0.08, 0.09, 0.07), CFrame.new(0.09, 0.845, 0.3, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#16181C", "SmoothPlastic"},
	{"FrontSight", "Slide", Vector3.new(0.06, 0.09, 0.06), CFrame.new(0, 0.885, -0.95, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#7CFF3A", "Neon"},
	{"Barrel", "Barrel", Vector3.new(0.17, 0.17, 0.46), CFrame.new(0, 0.66, -1.01, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#8A939F", "SmoothPlastic"},
	{"Bore", "Barrel", Vector3.new(0.09, 0.09, 0.02), CFrame.new(0, 0.66, -1.245, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#16181C", "SmoothPlastic"},
	{"Magazine", "Magazine", Vector3.new(0.22, 0.7, 0.3), CFrame.new(0, -0.102785, 0.09876, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#5C6673", "SmoothPlastic"},
	{"BasePlate", "Magazine", Vector3.new(0.3, 0.07, 0.42), CFrame.new(0, -0.471498, 0.19069, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#FF8C1A", "SmoothPlastic"},
	{"TopRound", "Magazine", Vector3.new(0.1, 0.06, 0.2), CFrame.new(0, 0.25625, -0.031982, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296), "#D9A934", "SmoothPlastic"},
	{"Trigger", "Trigger", Vector3.new(0.07, 0.2, 0.07), CFrame.new(0, 0.19, -0.42, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"TriggerShoe", "Trigger", Vector3.new(0.07, 0.06, 0.09), CFrame.new(0, 0.12, -0.45, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#5C6673", "SmoothPlastic"},
	{"Hammer", "Hammer", Vector3.new(0.1, 0.18, 0.08), CFrame.new(0, 0.58, 0.42, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#16181C", "SmoothPlastic"},
	{"HammerSpur", "Hammer", Vector3.new(0.12, 0.05, 0.1), CFrame.new(0, 0.665, 0.46, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#16181C", "SmoothPlastic"},
	{"SlideStop", "SlideStop", Vector3.new(0.03, 0.06, 0.22), CFrame.new(-0.155, 0.47, -0.23, 1, 0, 0, 0, 1, 0, 0, 0, 1), "#16181C", "SmoothPlastic"},
}

-- animated component -> pivot CFrame (relative to Handle)
local PIVOTS = {
	Slide = CFrame.new(0, 0.65, -0.36, 1, 0, 0, 0, 1, 0, 0, 0, 1),
	Barrel = CFrame.new(0, 0.66, -0.8, 1, 0, 0, 0, 1, 0, 0, 0, 1),
	Magazine = CFrame.new(0, -0.102785, 0.09876, 1, 0, 0, 0, 0.970296, 0.241922, 0, -0.241922, 0.970296),
	Trigger = CFrame.new(0, 0.28, -0.42, 1, 0, 0, 0, 1, 0, 0, 0, 1),
	Hammer = CFrame.new(0, 0.51, 0.42, 1, 0, 0, 0, 1, 0, 0, 0, 1),
	SlideStop = CFrame.new(-0.155, 0.47, -0.12, 1, 0, 0, 0, 1, 0, 0, 0, 1),
}

-- component main part, attachment name, CFrame (relative to Handle)
local ATTACHMENTS = {
	{"Barrel", "Muzzle", CFrame.new(0, 0.66, -1.26, 1, 0, 0, 0, 1, 0, 0, 0, 1)},
	{"Slide", "ShellEject", CFrame.new(0.18, 0.71, -0.12, 1, 0, 0, 0, 1, 0, 0, 0, 1)},
}

local old = PARENT:FindFirstChild("Rotstopper")
if old then old:Destroy() end

local tool = Instance.new("Tool")
tool.Name = "Rotstopper"
tool.RequiresHandle = true
tool.CanBeDropped = false
tool.Grip = CFrame.new()

local function newPart(name, size, cf)
	local p = Instance.new("Part")
	p.Name = name
	p.Size = size
	p.CFrame = cf
	p.Anchored = false
	p.CanCollide = false
	p.CanTouch = false
	p.CanQuery = false
	p.Massless = true
	p.CastShadow = true
	p.TopSurface = Enum.SurfaceType.Smooth
	p.BottomSurface = Enum.SurfaceType.Smooth
	return p
end

local handle = newPart("Handle", Vector3.new(0.28, 0.5, 0.36), CFrame.new())
handle.Transparency = 1
handle.Massless = false
handle.Parent = tool

local mains = {}
for _, d in ipairs(PARTS) do
	local name, comp = d[1], d[2]
	local p = newPart(name, d[3], d[4])
	p.Color = Color3.fromHex(d[5])
	p.Material = Enum.Material[d[6]]
	if name == comp then
		mains[comp] = p
		p.Parent = tool
	end
end

for _, d in ipairs(PARTS) do
	local name, comp = d[1], d[2]
	local main = mains[comp]
	local p = (name == comp) and main or nil
	if not p then
		p = newPart(name, d[3], d[4])
		p.Color = Color3.fromHex(d[5])
		p.Material = Enum.Material[d[6]]
		p.Parent = main
		local weld = Instance.new("Weld")
		weld.Name = name
		weld.Part0 = main
		weld.Part1 = p
		weld.C0 = main.CFrame:Inverse() * p.CFrame
		weld.Parent = p
	end
end

for comp, main in pairs(mains) do
	local pivot = PIVOTS[comp]
	if pivot then
		local m = Instance.new("Motor6D")
		m.Name = comp
		m.Part0 = handle
		m.Part1 = main
		m.C0 = handle.CFrame:Inverse() * pivot
		m.C1 = main.CFrame:Inverse() * pivot
		m.Parent = handle
	else
		local weld = Instance.new("Weld")
		weld.Name = comp
		weld.Part0 = handle
		weld.Part1 = main
		weld.C0 = handle.CFrame:Inverse() * main.CFrame
		weld.Parent = handle
	end
end

for _, a in ipairs(ATTACHMENTS) do
	local main = mains[a[1]]
	local att = Instance.new("Attachment")
	att.Name = a[2]
	att.CFrame = main.CFrame:Inverse() * a[3]
	att.Parent = main
end

if ADD_HAND_RIG_SCRIPT then
	-- Animations only drive tool parts if the tool is joined to the character by a Motor6D.
	-- This swaps the default RightGrip weld for a Motor6D named "Handle" while equipped.
	local s = Instance.new("Script")
	s.Name = "HandRig"
	s.Source = [==[
local tool = script.Parent
local motor

tool.Equipped:Connect(function()
	local character = tool.Parent
	local hand = character:FindFirstChild("RightHand") or character:FindFirstChild("Right Arm")
	if not hand then return end
	local grip = hand:FindFirstChild("RightGrip") or hand:WaitForChild("RightGrip", 2)
	if not grip then return end
	motor = Instance.new("Motor6D")
	motor.Name = "Handle"
	motor.Part0 = hand
	motor.Part1 = tool.Handle
	motor.C0 = grip.C0
	motor.C1 = grip.C1
	grip:Destroy()
	motor.Parent = hand
end)

tool.Unequipped:Connect(function()
	if motor then
		motor:Destroy()
		motor = nil
	end
end)
]==]
	s.Parent = tool
end

tool.Parent = PARENT
pcall(function() game:GetService("Selection"):Set({ tool }) end)
print(("Rotstopper built in %s: %d parts"):format(PARENT:GetFullName(), #PARTS + 1))
