--[[ Rotstopper rig. Run AFTER importing rotstopper.obj with the 3D Importer.
     1. Select the imported model in the Explorer.
     2. Paste this whole file into View > Command Bar and press Enter.
     It builds Tool "Rotstopper" in PARENT: an invisible Handle, Motor6Ds for the moving
     pieces (Slide, Barrel, Magazine, Trigger, Hammer, SlideStop), welds for Frame and Grip.
     Generated by tools/gen_rotstopper.py.
]]

local TEXTURE_ID = "" -- e.g. "rbxassetid://123456"; leave empty if the importer kept the texture
local PARENT = game:GetService("StarterPack")
local ADD_HAND_RIG_SCRIPT = true -- swaps RightGrip for a Motor6D on equip so animations reach the gun

-- mesh bounding-box centres and sizes, in the file's coordinates (studs)
local MESHES = {
	Frame = { center = Vector3.new(0, 0.28, -0.38), size = Vector3.new(0.4, 0.52, 1.88) },
	Grip = { center = Vector3.new(0, 0.02, 0.06), size = Vector3.new(0.4, 0.56, 0.76) },
	Slide = { center = Vector3.new(0, 0.82, -0.54), size = Vector3.new(0.4, 0.56, 1.8) },
	Barrel = { center = Vector3.new(0, 0.78, -1.12), size = Vector3.new(0.24, 0.16, 0.8) },
	Magazine = { center = Vector3.new(0, 0.02, 0.12), size = Vector3.new(0.32, 0.72, 0.64) },
	Trigger = { center = Vector3.new(0, 0.22, -0.48), size = Vector3.new(0.08, 0.24, 0.16) },
	Hammer = { center = Vector3.new(0, 0.64, 0.46), size = Vector3.new(0.16, 0.36, 0.2) },
	SlideStop = { center = Vector3.new(-0.18, 0.5, -0.52), size = Vector3.new(0.04, 0.08, 0.32) },
}
local HANDLE_SIZE = Vector3.new(0.32, 0.56, 0.44) -- the Handle sits at the file origin (grip centre)
local PIVOTS = {
	Slide = CFrame.new(0, 0.74, -0.52, 1, 0, 0, 0, 1, 0, 0, 0, 1),
	Barrel = CFrame.new(0, 0.76, -0.76, 1, 0, 0, 0, 1, 0, 0, 0, 1),
	Magazine = CFrame.new(0, -0.02, 0.04, 1, 0, 0, 0, 0.948683, 0.316228, 0, -0.316228, 0.948683),
	Trigger = CFrame.new(0, 0.3, -0.54, 1, 0, 0, 0, 1, 0, 0, 0, 1),
	Hammer = CFrame.new(0, 0.46, 0.4, 1, 0, 0, 0, 1, 0, 0, 0, 1),
	SlideStop = CFrame.new(-0.18, 0.48, -0.4, 1, 0, 0, 0, 1, 0, 0, 0, 1),
}
local ATTACHMENTS = {
	{ "Barrel", "Muzzle", Vector3.new(0, 0.76, -1.56) },
	{ "Slide", "ShellEject", Vector3.new(0.22, 0.84, -0.34) },
}

local model = game:GetService("Selection"):Get()[1]
assert(model, "Select the imported Rotstopper model in the Explorer first")

-- find each component by name (case-insensitive, tolerant of importer prefixes/suffixes)
local found = {}
for _, d in ipairs(model:GetDescendants()) do
	if d:IsA("MeshPart") then
		local lname = d.Name:lower()
		for comp in pairs(MESHES) do
			local lc = comp:lower()
			-- "Slide" must not match "SlideStop"
			local hit = lname:find(lc, 1, true) and not (lc == "slide" and lname:find("slidestop", 1, true))
			if hit and (not found[comp] or #d.Name < #found[comp].Name) then
				found[comp] = d
			end
		end
	end
end
local missing = {}
for comp in pairs(MESHES) do
	if not found[comp] then table.insert(missing, comp) end
end
assert(#missing == 0, "Could not find MeshParts named: " .. table.concat(missing, ", ") .. ". Rename them and run again.")

-- file -> world transform, measured from the imported pieces (handles importer scale and placement)
local frame, slide = found.Frame, found.Slide
local scale = (slide.Position - frame.Position).Magnitude / (MESHES.Slide.center - MESHES.Frame.center).Magnitude
local fileToWorld = frame.CFrame * CFrame.new(-MESHES.Frame.center * scale)
local function place(cf) -- file-space CFrame -> world, applying scale to the position
	return fileToWorld * (CFrame.new(cf.Position * scale) * cf.Rotation)
end

-- sanity check: every mesh should be where the file says it is
local worst = 0
for comp, info in pairs(MESHES) do
	local expected = fileToWorld * (info.center * scale)
	worst = math.max(worst, (found[comp].Position - expected).Magnitude / scale)
end
if worst > 0.02 then
	warn(("Rotstopper rig: imported pieces are up to %.3f studs off their expected layout. "
		.. "The importer may have rotated or re-centred them; check the result."):format(worst))
end

local old = PARENT:FindFirstChild("Rotstopper")
if old then old:Destroy() end
local tool = Instance.new("Tool")
tool.Name = "Rotstopper"
tool.RequiresHandle = true
tool.CanBeDropped = false
tool.Grip = CFrame.new()

local handle = Instance.new("Part")
handle.Name = "Handle"
handle.Size = HANDLE_SIZE * scale
handle.CFrame = place(CFrame.new())
handle.Transparency = 1
handle.CanCollide = false
handle.CanQuery = false
handle.CanTouch = false
handle.Parent = tool

for comp, part in pairs(found) do
	part.Name = comp
	part.Anchored = false
	part.CanCollide = false
	part.CanQuery = false
	part.CanTouch = false
	part.Massless = true
	if TEXTURE_ID ~= "" then part.TextureID = TEXTURE_ID end
	local pivot = PIVOTS[comp]
	if pivot then
		local p = place(pivot)
		local m = Instance.new("Motor6D")
		m.Name = comp
		m.Part0 = handle
		m.Part1 = part
		m.C0 = handle.CFrame:Inverse() * p
		m.C1 = part.CFrame:Inverse() * p
		m.Parent = handle
	else
		local wld = Instance.new("Weld")
		wld.Name = comp
		wld.Part0 = handle
		wld.Part1 = part
		wld.C0 = handle.CFrame:Inverse() * part.CFrame
		wld.Parent = handle
	end
	part.Parent = tool
end

for _, a in ipairs(ATTACHMENTS) do
	local part = found[a[1]]
	local att = Instance.new("Attachment")
	att.Name = a[2]
	att.CFrame = part.CFrame:Inverse() * place(CFrame.new(a[3]))
	att.Parent = part
end

if ADD_HAND_RIG_SCRIPT then
	local s = Instance.new("Script")
	s.Name = "HandRig"
	s.Source = [==[
local tool = script.Parent
local motor

tool.Equipped:Connect(function()
	local character = tool.Parent
	local hand = character:FindFirstChild("RightHand") or character:FindFirstChild("Right Arm")
	if not hand then return end
	local grip = hand:FindFirstChild("RightGrip") or hand:WaitForChild("RightGrip", 2)
	if not grip then return end
	motor = Instance.new("Motor6D")
	motor.Name = "Handle"
	motor.Part0 = hand
	motor.Part1 = tool.Handle
	motor.C0 = grip.C0
	motor.C1 = grip.C1
	grip:Destroy()
	motor.Parent = hand
end)

tool.Unequipped:Connect(function()
	if motor then
		motor:Destroy()
		motor = nil
	end
end)
]==]
	s.Parent = tool
end

tool.Parent = PARENT
if #model:GetChildren() == 0 then model:Destroy() end
pcall(function() game:GetService("Selection"):Set({ tool }) end)
print(("Rotstopper rigged in %s (scale %.3f, layout error %.4f studs)"):format(PARENT:GetFullName(), scale, worst))
