package com.rimeheart.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/** GENERATED by tools/gen_models.py — do not edit by hand. */
@SuppressWarnings("unused")
public final class ModelDefs {
    private ModelDefs() {}

    public static LayerDefinition createFrostWraith() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, 0.0F, -2.5F, 8.0F, 10.0F, 5.0F), PartPose.offsetAndRotation(0.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(26, 0).addBox(-3.5F, -8.0F, -3.5F, 7.0F, 8.0F, 7.0F).texOffs(0, 29).addBox(-4.0F, -8.5F, -1.0F, 8.0F, 3.0F, 5.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 15).addBox(0.0F, 0.0F, -1.5F, 3.0F, 11.0F, 3.0F), PartPose.offsetAndRotation(4.5F, 1.0F, 0.0F, -0.35F, 0.0F, -0.12F));
        PartDefinition p_left_claw = p_left_arm.addOrReplaceChild("left_claw", CubeListBuilder.create().texOffs(26, 29).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 3.0F, 2.0F), PartPose.offsetAndRotation(1.5F, 11.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(12, 15).mirror().addBox(-3.0F, 0.0F, -1.5F, 3.0F, 11.0F, 3.0F).mirror(false), PartPose.offsetAndRotation(-4.5F, 1.0F, 0.0F, -0.35F, 0.0F, 0.12F));
        PartDefinition p_right_claw = p_right_arm.addOrReplaceChild("right_claw", CubeListBuilder.create().texOffs(34, 29).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 3.0F, 2.0F), PartPose.offsetAndRotation(-1.5F, 11.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_body.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(24, 15).addBox(-3.5F, 0.0F, -2.0F, 7.0F, 6.0F, 4.0F), PartPose.offsetAndRotation(0.0F, 10.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail2 = p_tail.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(46, 15).addBox(-2.5F, 0.0F, -1.5F, 5.0F, 6.0F, 3.0F), PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition createShardling() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-3.5F, -3.0F, -4.0F, 7.0F, 4.0F, 8.0F), PartPose.offsetAndRotation(0.0F, 21.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_spikes = p_body.addOrReplaceChild("spikes", CubeListBuilder.create().texOffs(30, 0).addBox(-1.0F, -4.0F, -2.0F, 2.0F, 4.0F, 2.0F).texOffs(54, 0).addBox(-2.5F, -3.0F, 1.0F, 2.0F, 3.0F, 2.0F).texOffs(0, 12).addBox(1.0F, -3.0F, 0.0F, 2.0F, 3.0F, 2.0F).texOffs(8, 12).addBox(-0.5F, -2.0F, 2.5F, 1.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -3.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(38, 0).addBox(-2.5F, -2.0F, -3.0F, 5.0F, 3.0F, 3.0F), PartPose.offsetAndRotation(0.0F, -1.0F, -4.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_leg0 = p_body.addOrReplaceChild("leg0", CubeListBuilder.create().texOffs(12, 12).addBox(0.0F, -0.5F, -0.5F, 5.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(3.5F, -1.0F, -2.5F, 0.0F, 0.0F, 0.55F));
        PartDefinition p_leg1 = p_body.addOrReplaceChild("leg1", CubeListBuilder.create().texOffs(24, 12).addBox(0.0F, -0.5F, -0.5F, 5.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(3.5F, -1.0F, 0.0F, 0.0F, 0.0F, 0.55F));
        PartDefinition p_leg2 = p_body.addOrReplaceChild("leg2", CubeListBuilder.create().texOffs(36, 12).addBox(0.0F, -0.5F, -0.5F, 5.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(3.5F, -1.0F, 2.5F, 0.0F, 0.0F, 0.55F));
        PartDefinition p_leg3 = p_body.addOrReplaceChild("leg3", CubeListBuilder.create().texOffs(48, 12).addBox(-5.0F, -0.5F, -0.5F, 5.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-3.5F, -1.0F, -2.5F, 0.0F, 0.0F, -0.55F));
        PartDefinition p_leg4 = p_body.addOrReplaceChild("leg4", CubeListBuilder.create().texOffs(0, 17).addBox(-5.0F, -0.5F, -0.5F, 5.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-3.5F, -1.0F, 0.0F, 0.0F, 0.0F, -0.55F));
        PartDefinition p_leg5 = p_body.addOrReplaceChild("leg5", CubeListBuilder.create().texOffs(12, 17).addBox(-5.0F, -0.5F, -0.5F, 5.0F, 1.0F, 1.0F), PartPose.offsetAndRotation(-3.5F, -1.0F, 2.5F, 0.0F, 0.0F, -0.55F));
        return LayerDefinition.create(mesh, 64, 32);
    }

    public static LayerDefinition createFrostSovereign() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-8.0F, -14.0F, -4.5F, 16.0F, 14.0F, 9.0F).texOffs(0, 56).addBox(-6.0F, 0.0F, -3.5F, 12.0F, 6.0F, 7.0F), PartPose.offsetAndRotation(0.0F, -8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(50, 0).addBox(-5.0F, -10.0F, -5.0F, 10.0F, 10.0F, 10.0F).texOffs(116, 69).addBox(-5.0F, -15.0F, -5.0F, 2.0F, 5.0F, 2.0F).texOffs(24, 69).addBox(-1.0F, -18.0F, -5.0F, 2.0F, 8.0F, 2.0F).texOffs(0, 80).addBox(3.0F, -15.0F, -5.0F, 2.0F, 5.0F, 2.0F).texOffs(8, 80).addBox(-4.0F, -14.0F, 3.0F, 2.0F, 4.0F, 2.0F).texOffs(16, 80).addBox(2.0F, -14.0F, 3.0F, 2.0F, 4.0F, 2.0F).texOffs(38, 56).addBox(-5.5F, -11.0F, -5.5F, 11.0F, 1.0F, 11.0F), PartPose.offsetAndRotation(0.0F, -14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(28, 23).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 12.0F, 6.0F), PartPose.offsetAndRotation(11.0F, -12.0F, 0.0F, 0.0F, 0.0F, -0.12F));
        PartDefinition p_left_forearm = p_left_arm.addOrReplaceChild("left_forearm", CubeListBuilder.create().texOffs(90, 0).addBox(-3.5F, 0.0F, -3.5F, 7.0F, 12.0F, 7.0F), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_hand = p_left_forearm.addOrReplaceChild("left_hand", CubeListBuilder.create().texOffs(82, 56).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 5.0F, 6.0F).texOffs(24, 80).addBox(-3.0F, 5.0F, -2.5F, 1.5F, 4.0F, 1.5F).texOffs(30, 80).addBox(-0.8F, 5.0F, -2.5F, 1.5F, 4.0F, 1.5F).texOffs(36, 80).addBox(1.4F, 5.0F, -2.5F, 1.5F, 4.0F, 1.5F), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(52, 23).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 12.0F, 6.0F), PartPose.offsetAndRotation(-11.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.12F));
        PartDefinition p_right_forearm = p_right_arm.addOrReplaceChild("right_forearm", CubeListBuilder.create().texOffs(0, 23).addBox(-3.5F, 0.0F, -3.5F, 7.0F, 12.0F, 7.0F), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_hand = p_right_forearm.addOrReplaceChild("right_hand", CubeListBuilder.create().texOffs(0, 69).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 5.0F, 6.0F).texOffs(42, 80).addBox(-3.0F, 5.0F, -2.5F, 1.5F, 4.0F, 1.5F).texOffs(48, 80).addBox(-0.8F, 5.0F, -2.5F, 1.5F, 4.0F, 1.5F).texOffs(54, 80).addBox(1.4F, 5.0F, -2.5F, 1.5F, 4.0F, 1.5F), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_skirt = p_body.addOrReplaceChild("skirt", CubeListBuilder.create().texOffs(76, 23).addBox(-7.0F, 0.0F, -4.0F, 14.0F, 8.0F, 8.0F), PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_skirt2 = p_skirt.addOrReplaceChild("skirt2", CubeListBuilder.create().texOffs(0, 42).addBox(-5.0F, 0.0F, -3.0F, 10.0F, 8.0F, 6.0F), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_skirt3 = p_skirt2.addOrReplaceChild("skirt3", CubeListBuilder.create().texOffs(32, 69).addBox(-3.0F, 0.0F, -2.0F, 6.0F, 6.0F, 4.0F), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_pauldron = p_body.addOrReplaceChild("left_pauldron", CubeListBuilder.create().texOffs(32, 42).addBox(-2.0F, -4.0F, -4.0F, 8.0F, 6.0F, 8.0F).texOffs(100, 69).addBox(1.0F, -10.0F, -1.0F, 2.0F, 6.0F, 2.0F).texOffs(60, 80).addBox(4.0F, -8.0F, 1.5F, 2.0F, 4.0F, 2.0F), PartPose.offsetAndRotation(10.0F, -13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_pauldron = p_body.addOrReplaceChild("right_pauldron", CubeListBuilder.create().texOffs(64, 42).addBox(-6.0F, -4.0F, -4.0F, 8.0F, 6.0F, 8.0F).texOffs(108, 69).addBox(-3.0F, -10.0F, -1.0F, 2.0F, 6.0F, 2.0F).texOffs(68, 80).addBox(-6.0F, -8.0F, 1.5F, 2.0F, 4.0F, 2.0F), PartPose.offsetAndRotation(-10.0F, -13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_orbit = root.addOrReplaceChild("orbit", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, -18.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard0 = p_orbit.addOrReplaceChild("shard0", CubeListBuilder.create().texOffs(52, 69).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 8.0F, 2.0F), PartPose.offsetAndRotation(18.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard1 = p_orbit.addOrReplaceChild("shard1", CubeListBuilder.create().texOffs(60, 69).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 8.0F, 2.0F), PartPose.offsetAndRotation(9.0F, 3.0F, 15.6F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard2 = p_orbit.addOrReplaceChild("shard2", CubeListBuilder.create().texOffs(68, 69).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 8.0F, 2.0F), PartPose.offsetAndRotation(-9.0F, -0.8F, 15.6F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard3 = p_orbit.addOrReplaceChild("shard3", CubeListBuilder.create().texOffs(76, 69).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 8.0F, 2.0F), PartPose.offsetAndRotation(-18.0F, -2.8F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard4 = p_orbit.addOrReplaceChild("shard4", CubeListBuilder.create().texOffs(84, 69).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 8.0F, 2.0F), PartPose.offsetAndRotation(-9.0F, 1.5F, -15.6F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard5 = p_orbit.addOrReplaceChild("shard5", CubeListBuilder.create().texOffs(92, 69).addBox(-1.0F, -4.0F, -1.0F, 2.0F, 8.0F, 2.0F), PartPose.offsetAndRotation(9.0F, 2.4F, -15.6F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

}
