package com.oathbound.client;

import com.oathbound.client.model.FaunaModels;
import com.oathbound.client.render.Renderers;
import com.oathbound.registry.ModEntities;
import net.minecraftforge.client.event.EntityRenderersEvent;

/** GENERATED by tools/oath/roster.py: renderers for the wider roster. */
public final class RosterRenderers {
    private RosterRenderers() {}

    public static void register(EntityRenderersEvent.RegisterRenderers e) {
        e.registerEntityRenderer(ModEntities.GLIMMERFAWN.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Quadruped(r, "glimmerfawn", 1.0f, false, 0.9f), "glimmerfawn", 0.5f, 1.0f));
        e.registerEntityRenderer(ModEntities.DUSKHARE.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Quadruped(r, "duskhare", 1.0f, true, 0.3f), "duskhare", 0.25f, 1.0f));
        e.registerEntityRenderer(ModEntities.MOSSBACK_TORTOISE.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Quadruped(r, "mossback_tortoise", 0.6f, false, 0.7f), "mossback_tortoise", 0.7f, 1.0f));
        e.registerEntityRenderer(ModEntities.LUMEN_BEETLE.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Crawler(r, "lumen_beetle"), "lumen_beetle", 0.15f, 1.0f));
        e.registerEntityRenderer(ModEntities.TIDEWADER.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Bird(r, "tidewader"), "tidewader", 0.35f, 1.0f));
        e.registerEntityRenderer(ModEntities.THORNBACK_BOAR.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Quadruped(r, "thornback_boar", 1.1f, false, 0.45f), "thornback_boar", 0.6f, 1.0f));
        e.registerEntityRenderer(ModEntities.STONEWARDEN.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Biped(r, "stonewarden", 0.7f, 0.1f), "stonewarden", 1.0f, 1.3f));
        e.registerEntityRenderer(ModEntities.RUNEWISP.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Floater(r, "runewisp"), "runewisp", 0.0f, 1.0f));
        e.registerEntityRenderer(ModEntities.DROWNED_CHOIRMONK.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Biped(r, "drowned_choirmonk", 0.8f, 0.0f), "drowned_choirmonk", 0.5f, 1.0f));
        e.registerEntityRenderer(ModEntities.MIRE_HAG.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Biped(r, "mire_hag", 0.8f, 0.35f), "mire_hag", 0.5f, 1.0f));
        e.registerEntityRenderer(ModEntities.GRAVE_CRAWLER.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Crawler(r, "grave_crawler"), "grave_crawler", 0.5f, 1.0f));
        e.registerEntityRenderer(ModEntities.GLOAM_STALKER.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Quadruped(r, "gloam_stalker", 1.2f, false, -0.2f), "gloam_stalker", 0.5f, 1.0f));
        e.registerEntityRenderer(ModEntities.SHADE_WRAITH.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Floater(r, "shade_wraith"), "shade_wraith", 0.0f, 1.0f));
        e.registerEntityRenderer(ModEntities.LUMENITE_MITE.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Crawler(r, "lumenite_mite"), "lumenite_mite", 0.25f, 1.0f));
        e.registerEntityRenderer(ModEntities.ASHEN_REVENANT.get(), c -> new Renderers.Fauna<>(c, r -> new FaunaModels.Biped(r, "ashen_revenant", 1.0f, 0.0f), "ashen_revenant", 0.5f, 1.0f));
    }
}
