package com.astralfall.client.model;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/** GENERATED by tools/gen_models.py — do not edit by hand. */
@SuppressWarnings("unused")
public final class ModelDefs {
    private ModelDefs() {}

    public static LayerDefinition createAstralWisp() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(32, 0).addBox(-3.0F, -3.0F, -3.0F, 6.0F, 6.0F, 6.0F).texOffs(0, 0).addBox(-4.0F, -4.0F, -4.0F, 8.0F, 8.0F, 8.0F), PartPose.offsetAndRotation(0.0F, 16.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_wing = p_body.addOrReplaceChild("left_wing", CubeListBuilder.create().texOffs(0, 16).addBox(0.0F, -4.0F, 0.0F, 7.0F, 7.0F, 0.0F), PartPose.offsetAndRotation(3.0F, -1.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_wing = p_body.addOrReplaceChild("right_wing", CubeListBuilder.create().texOffs(14, 16).mirror().addBox(-7.0F, -4.0F, 0.0F, 7.0F, 7.0F, 0.0F).mirror(false), PartPose.offsetAndRotation(-3.0F, -1.0F, 1.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail1 = p_body.addOrReplaceChild("tail1", CubeListBuilder.create().texOffs(28, 16).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 3.0F, 4.0F), PartPose.offsetAndRotation(0.0F, 3.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail2 = p_tail1.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(44, 16).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 3.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 3.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail3 = p_tail2.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(52, 16).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 3.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_orbit = p_body.addOrReplaceChild("orbit", CubeListBuilder.create().texOffs(0, 23).addBox(6.0F, -1.0F, -1.0F, 2.0F, 2.0F, 2.0F).texOffs(8, 23).addBox(-8.0F, 0.0F, -1.0F, 2.0F, 2.0F, 2.0F).texOffs(16, 23).addBox(-1.0F, -2.0F, 6.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition createVoidStalker() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(16, 24).addBox(-3.5F, -12.0F, -1.5F, 7.0F, 12.0F, 3.0F), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.18F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(32, 0).addBox(-3.0F, -11.0F, -3.0F, 6.0F, 11.0F, 6.0F), PartPose.offsetAndRotation(0.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_body.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(0, 0).addBox(0.0F, -1.0F, -1.0F, 2.0F, 22.0F, 2.0F), PartPose.offsetAndRotation(4.5F, -11.0F, 0.0F, 0.0F, 0.0F, -0.08F));
        PartDefinition p_left_claw = p_left_arm.addOrReplaceChild("left_claw", CubeListBuilder.create().texOffs(44, 24).addBox(-1.5F, 0.0F, -1.5F, 1.0F, 5.0F, 1.0F).texOffs(36, 24).addBox(0.5F, 0.0F, -1.5F, 1.0F, 6.0F, 1.0F).texOffs(52, 24).addBox(-0.5F, 0.0F, 0.5F, 1.0F, 4.0F, 1.0F), PartPose.offsetAndRotation(1.0F, 21.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_body.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(8, 0).addBox(-2.0F, -1.0F, -1.0F, 2.0F, 22.0F, 2.0F), PartPose.offsetAndRotation(-4.5F, -11.0F, 0.0F, 0.0F, 0.0F, 0.08F));
        PartDefinition p_right_claw = p_right_arm.addOrReplaceChild("right_claw", CubeListBuilder.create().texOffs(48, 24).addBox(-1.5F, 0.0F, -1.5F, 1.0F, 5.0F, 1.0F).texOffs(40, 24).addBox(0.5F, 0.0F, -1.5F, 1.0F, 6.0F, 1.0F).texOffs(56, 24).addBox(-0.5F, 0.0F, 0.5F, 1.0F, 4.0F, 1.0F), PartPose.offsetAndRotation(-1.0F, 21.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_cape = p_body.addOrReplaceChild("cape", CubeListBuilder.create().texOffs(0, 24).addBox(-4.0F, 0.0F, 0.0F, 8.0F, 16.0F, 0.0F), PartPose.offsetAndRotation(0.0F, -12.0F, 1.6F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create().texOffs(16, 0).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 16.0F, 2.0F), PartPose.offsetAndRotation(2.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create().texOffs(24, 0).mirror().addBox(-1.0F, 0.0F, -1.0F, 2.0F, 16.0F, 2.0F).mirror(false), PartPose.offsetAndRotation(-2.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

    public static LayerDefinition createMeteoriteCrawler() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-7.0F, -4.0F, -8.0F, 14.0F, 8.0F, 16.0F).texOffs(60, 0).addBox(-5.0F, -7.0F, -5.0F, 10.0F, 3.0F, 10.0F).texOffs(48, 24).addBox(-2.0F, -9.0F, -2.0F, 4.0F, 2.0F, 4.0F).texOffs(88, 24).addBox(3.0F, -6.0F, 4.0F, 3.0F, 2.0F, 3.0F).texOffs(100, 24).addBox(-6.0F, -6.0F, -6.0F, 3.0F, 2.0F, 3.0F), PartPose.offsetAndRotation(0.0F, 15.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(100, 0).addBox(-4.0F, -3.0F, -6.0F, 8.0F, 6.0F, 6.0F), PartPose.offsetAndRotation(0.0F, 1.0F, -8.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_mandible = p_head.addOrReplaceChild("left_mandible", CubeListBuilder.create().texOffs(64, 24).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 4.0F), PartPose.offsetAndRotation(2.5F, 2.0F, -6.0F, 0.0F, -0.3F, 0.0F));
        PartDefinition p_right_mandible = p_head.addOrReplaceChild("right_mandible", CubeListBuilder.create().texOffs(76, 24).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 4.0F), PartPose.offsetAndRotation(-2.5F, 2.0F, -6.0F, 0.0F, 0.3F, 0.0F));
        PartDefinition p_left_leg0 = p_body.addOrReplaceChild("left_leg0", CubeListBuilder.create().texOffs(0, 35).addBox(0.0F, -1.0F, -1.0F, 8.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(6.0F, 2.0F, -5.0F, 0.0F, -0.35F, 0.45F));
        PartDefinition p_left_leg0_lower = p_left_leg0.addOrReplaceChild("left_leg0_lower", CubeListBuilder.create().texOffs(0, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(8.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.25F));
        PartDefinition p_left_leg1 = p_body.addOrReplaceChild("left_leg1", CubeListBuilder.create().texOffs(20, 35).addBox(0.0F, -1.0F, -1.0F, 8.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(6.0F, 2.0F, 0.0F, 0.0F, 0.0F, 0.45F));
        PartDefinition p_left_leg1_lower = p_left_leg1.addOrReplaceChild("left_leg1_lower", CubeListBuilder.create().texOffs(8, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(8.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.25F));
        PartDefinition p_left_leg2 = p_body.addOrReplaceChild("left_leg2", CubeListBuilder.create().texOffs(40, 35).addBox(0.0F, -1.0F, -1.0F, 8.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(6.0F, 2.0F, 5.0F, 0.0F, 0.35F, 0.45F));
        PartDefinition p_left_leg2_lower = p_left_leg2.addOrReplaceChild("left_leg2_lower", CubeListBuilder.create().texOffs(16, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(8.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.25F));
        PartDefinition p_right_leg0 = p_body.addOrReplaceChild("right_leg0", CubeListBuilder.create().texOffs(60, 35).addBox(-8.0F, -1.0F, -1.0F, 8.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(-6.0F, 2.0F, -5.0F, 0.0F, 0.35F, -0.45F));
        PartDefinition p_right_leg0_lower = p_right_leg0.addOrReplaceChild("right_leg0_lower", CubeListBuilder.create().texOffs(24, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(-8.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.25F));
        PartDefinition p_right_leg1 = p_body.addOrReplaceChild("right_leg1", CubeListBuilder.create().texOffs(80, 35).addBox(-8.0F, -1.0F, -1.0F, 8.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(-6.0F, 2.0F, 0.0F, 0.0F, -0.0F, -0.45F));
        PartDefinition p_right_leg1_lower = p_right_leg1.addOrReplaceChild("right_leg1_lower", CubeListBuilder.create().texOffs(32, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(-8.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.25F));
        PartDefinition p_right_leg2 = p_body.addOrReplaceChild("right_leg2", CubeListBuilder.create().texOffs(100, 35).addBox(-8.0F, -1.0F, -1.0F, 8.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(-6.0F, 2.0F, 5.0F, 0.0F, -0.35F, -0.45F));
        PartDefinition p_right_leg2_lower = p_right_leg2.addOrReplaceChild("right_leg2_lower", CubeListBuilder.create().texOffs(40, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 9.0F, 2.0F), PartPose.offsetAndRotation(-8.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.25F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition createVoidGazer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-6.0F, -6.0F, -6.0F, 12.0F, 12.0F, 12.0F).texOffs(48, 0).addBox(-5.0F, -7.0F, -5.0F, 10.0F, 1.0F, 10.0F).texOffs(88, 0).addBox(-5.0F, 6.0F, -5.0F, 10.0F, 1.0F, 10.0F).texOffs(48, 31).addBox(-1.0F, -9.0F, -1.0F, 2.0F, 3.0F, 2.0F).texOffs(56, 31).addBox(-5.0F, -8.0F, -3.0F, 2.0F, 2.0F, 2.0F).texOffs(64, 31).addBox(3.0F, -8.0F, -3.0F, 2.0F, 2.0F, 2.0F).texOffs(72, 31).addBox(-4.0F, -8.0F, 2.0F, 2.0F, 2.0F, 2.0F).texOffs(80, 31).addBox(2.0F, -8.0F, 2.0F, 2.0F, 2.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 12.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_top_lid = p_body.addOrReplaceChild("top_lid", CubeListBuilder.create().texOffs(0, 24).addBox(-6.5F, 0.0F, -1.0F, 13.0F, 6.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -6.0F, -6.2F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_bottom_lid = p_body.addOrReplaceChild("bottom_lid", CubeListBuilder.create().texOffs(28, 24).addBox(-6.5F, -6.0F, -1.0F, 13.0F, 6.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 6.0F, -6.2F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle0 = p_body.addOrReplaceChild("tentacle0", CubeListBuilder.create().texOffs(56, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(3.5F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle0_b = p_tentacle0.addOrReplaceChild("tentacle0_b", CubeListBuilder.create().texOffs(64, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle0_c = p_tentacle0_b.addOrReplaceChild("tentacle0_c", CubeListBuilder.create().texOffs(24, 31).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 5.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle1 = p_body.addOrReplaceChild("tentacle1", CubeListBuilder.create().texOffs(72, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(1.8F, 5.0F, 3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle1_b = p_tentacle1.addOrReplaceChild("tentacle1_b", CubeListBuilder.create().texOffs(80, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle1_c = p_tentacle1_b.addOrReplaceChild("tentacle1_c", CubeListBuilder.create().texOffs(28, 31).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 5.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle2 = p_body.addOrReplaceChild("tentacle2", CubeListBuilder.create().texOffs(88, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(-1.7F, 5.0F, 3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle2_b = p_tentacle2.addOrReplaceChild("tentacle2_b", CubeListBuilder.create().texOffs(96, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle2_c = p_tentacle2_b.addOrReplaceChild("tentacle2_c", CubeListBuilder.create().texOffs(32, 31).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 5.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle3 = p_body.addOrReplaceChild("tentacle3", CubeListBuilder.create().texOffs(104, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(-3.5F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle3_b = p_tentacle3.addOrReplaceChild("tentacle3_b", CubeListBuilder.create().texOffs(112, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle3_c = p_tentacle3_b.addOrReplaceChild("tentacle3_c", CubeListBuilder.create().texOffs(36, 31).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 5.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle4 = p_body.addOrReplaceChild("tentacle4", CubeListBuilder.create().texOffs(120, 24).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(-1.8F, 5.0F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle4_b = p_tentacle4.addOrReplaceChild("tentacle4_b", CubeListBuilder.create().texOffs(0, 31).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle4_c = p_tentacle4_b.addOrReplaceChild("tentacle4_c", CubeListBuilder.create().texOffs(40, 31).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 5.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle5 = p_body.addOrReplaceChild("tentacle5", CubeListBuilder.create().texOffs(8, 31).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(1.8F, 5.0F, -3.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle5_b = p_tentacle5.addOrReplaceChild("tentacle5_b", CubeListBuilder.create().texOffs(16, 31).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tentacle5_c = p_tentacle5_b.addOrReplaceChild("tentacle5_c", CubeListBuilder.create().texOffs(44, 31).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 5.0F, 1.0F), PartPose.offsetAndRotation(0.0F, 5.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    public static LayerDefinition createAstraeus() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_torso = root.addOrReplaceChild("torso", CubeListBuilder.create().texOffs(0, 0).addBox(-10.0F, -16.0F, -5.0F, 20.0F, 16.0F, 10.0F).texOffs(128, 43).addBox(-3.0F, -12.0F, -6.0F, 6.0F, 6.0F, 1.0F).texOffs(80, 26).addBox(-7.0F, 0.0F, -4.0F, 14.0F, 6.0F, 8.0F), PartPose.offsetAndRotation(0.0F, -14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_head = p_torso.addOrReplaceChild("head", CubeListBuilder.create().texOffs(60, 0).addBox(-6.0F, -12.0F, -6.0F, 12.0F, 12.0F, 12.0F).texOffs(190, 43).addBox(-6.0F, -15.0F, -6.0F, 2.0F, 4.0F, 2.0F).texOffs(112, 43).addBox(-1.0F, -18.0F, -6.0F, 2.0F, 7.0F, 2.0F).texOffs(198, 43).addBox(4.0F, -15.0F, -6.0F, 2.0F, 4.0F, 2.0F).texOffs(206, 43).addBox(-6.0F, -14.0F, 3.0F, 2.0F, 3.0F, 2.0F).texOffs(214, 43).addBox(4.0F, -14.0F, 3.0F, 2.0F, 3.0F, 2.0F).texOffs(0, 43).addBox(-6.0F, -12.0F, -6.0F, 12.0F, 1.0F, 12.0F), PartPose.offsetAndRotation(0.0F, -16.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_halo = p_head.addOrReplaceChild("halo", CubeListBuilder.create().texOffs(222, 43).addBox(9.0F, -1.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(228, 43).addBox(8.0F, 4.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(234, 43).addBox(4.0F, 8.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(240, 43).addBox(-1.0F, 9.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(246, 43).addBox(-6.0F, 8.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(0, 56).addBox(-10.0F, 4.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(6, 56).addBox(-11.0F, -1.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(12, 56).addBox(-10.0F, -6.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(18, 56).addBox(-6.0F, -10.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(24, 56).addBox(-1.0F, -11.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(30, 56).addBox(4.0F, -10.0F, 0.0F, 2.0F, 2.0F, 1.0F).texOffs(36, 56).addBox(8.0F, -6.0F, 0.0F, 2.0F, 2.0F, 1.0F), PartPose.offsetAndRotation(0.0F, -6.0F, 7.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_arm = p_torso.addOrReplaceChild("left_arm", CubeListBuilder.create().texOffs(164, 0).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 13.0F, 6.0F), PartPose.offsetAndRotation(15.0F, -12.0F, 0.0F, 0.0F, 0.0F, -0.15F));
        PartDefinition p_left_forearm = p_left_arm.addOrReplaceChild("left_forearm", CubeListBuilder.create().texOffs(108, 0).addBox(-3.5F, 0.0F, -3.5F, 7.0F, 13.0F, 7.0F), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_hand = p_left_forearm.addOrReplaceChild("left_hand", CubeListBuilder.create().texOffs(124, 26).addBox(-4.0F, 0.0F, -4.0F, 8.0F, 6.0F, 8.0F).texOffs(142, 43).addBox(-4.0F, 5.0F, -3.5F, 2.0F, 5.0F, 2.0F).texOffs(150, 43).addBox(-1.0F, 5.0F, -3.5F, 2.0F, 5.0F, 2.0F).texOffs(158, 43).addBox(2.0F, 5.0F, -3.5F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_arm = p_torso.addOrReplaceChild("right_arm", CubeListBuilder.create().texOffs(188, 0).addBox(-3.0F, 0.0F, -3.0F, 6.0F, 13.0F, 6.0F), PartPose.offsetAndRotation(-15.0F, -12.0F, 0.0F, 0.0F, 0.0F, 0.15F));
        PartDefinition p_right_forearm = p_right_arm.addOrReplaceChild("right_forearm", CubeListBuilder.create().texOffs(136, 0).addBox(-3.5F, 0.0F, -3.5F, 7.0F, 13.0F, 7.0F), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_hand = p_right_forearm.addOrReplaceChild("right_hand", CubeListBuilder.create().texOffs(156, 26).addBox(-4.0F, 0.0F, -4.0F, 8.0F, 6.0F, 8.0F).texOffs(166, 43).addBox(-4.0F, 5.0F, -3.5F, 2.0F, 5.0F, 2.0F).texOffs(174, 43).addBox(-1.0F, 5.0F, -3.5F, 2.0F, 5.0F, 2.0F).texOffs(182, 43).addBox(2.0F, 5.0F, -3.5F, 2.0F, 5.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 13.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_left_pauldron = p_torso.addOrReplaceChild("left_pauldron", CubeListBuilder.create().texOffs(212, 0).addBox(-2.0F, -3.0F, -5.0F, 10.0F, 7.0F, 10.0F), PartPose.offsetAndRotation(12.0F, -14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_right_pauldron = p_torso.addOrReplaceChild("right_pauldron", CubeListBuilder.create().texOffs(0, 26).addBox(-8.0F, -3.0F, -5.0F, 10.0F, 7.0F, 10.0F), PartPose.offsetAndRotation(-12.0F, -14.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail = p_torso.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(40, 26).addBox(-6.0F, 0.0F, -4.0F, 12.0F, 8.0F, 8.0F), PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail2 = p_tail.addOrReplaceChild("tail2", CubeListBuilder.create().texOffs(188, 26).addBox(-4.0F, 0.0F, -3.0F, 8.0F, 8.0F, 6.0F), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail3 = p_tail2.addOrReplaceChild("tail3", CubeListBuilder.create().texOffs(48, 43).addBox(-2.0F, 0.0F, -2.0F, 4.0F, 8.0F, 4.0F), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_tail4 = p_tail3.addOrReplaceChild("tail4", CubeListBuilder.create().texOffs(120, 43).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 6.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 8.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_orbit = root.addOrReplaceChild("orbit", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, -22.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard0 = p_orbit.addOrReplaceChild("shard0", CubeListBuilder.create().texOffs(64, 43).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(22.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard1 = p_orbit.addOrReplaceChild("shard1", CubeListBuilder.create().texOffs(72, 43).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(11.0F, 0.0F, 19.1F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard2 = p_orbit.addOrReplaceChild("shard2", CubeListBuilder.create().texOffs(80, 43).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(-11.0F, 0.0F, 19.1F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard3 = p_orbit.addOrReplaceChild("shard3", CubeListBuilder.create().texOffs(88, 43).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(-22.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard4 = p_orbit.addOrReplaceChild("shard4", CubeListBuilder.create().texOffs(96, 43).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(-11.0F, 0.0F, -19.1F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_shard5 = p_orbit.addOrReplaceChild("shard5", CubeListBuilder.create().texOffs(104, 43).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(11.0F, 0.0F, -19.1F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 256, 128);
    }

    public static LayerDefinition createMeteor() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_rock = root.addOrReplaceChild("rock", CubeListBuilder.create().texOffs(0, 0).addBox(-8.0F, -8.0F, -8.0F, 16.0F, 16.0F, 16.0F).texOffs(64, 0).addBox(-10.0F, -5.0F, -5.0F, 2.0F, 10.0F, 10.0F).texOffs(88, 0).addBox(8.0F, -6.0F, -4.0F, 2.0F, 9.0F, 8.0F).texOffs(0, 32).addBox(-5.0F, -10.0F, -6.0F, 10.0F, 2.0F, 12.0F).texOffs(44, 32).addBox(-6.0F, 8.0F, -5.0F, 12.0F, 2.0F, 10.0F).texOffs(0, 46).addBox(-5.0F, -4.0F, -10.0F, 10.0F, 9.0F, 2.0F).texOffs(88, 32).addBox(-4.0F, -6.0F, 8.0F, 8.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition createMeteorStar() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_rock = root.addOrReplaceChild("rock", CubeListBuilder.create().texOffs(0, 0).addBox(-8.0F, -8.0F, -8.0F, 16.0F, 16.0F, 16.0F).texOffs(64, 0).addBox(-10.0F, -5.0F, -5.0F, 2.0F, 10.0F, 10.0F).texOffs(88, 0).addBox(8.0F, -6.0F, -4.0F, 2.0F, 9.0F, 8.0F).texOffs(0, 32).addBox(-5.0F, -10.0F, -6.0F, 10.0F, 2.0F, 12.0F).texOffs(44, 32).addBox(-6.0F, 8.0F, -5.0F, 12.0F, 2.0F, 10.0F).texOffs(0, 46).addBox(-5.0F, -4.0F, -10.0F, 10.0F, 9.0F, 2.0F).texOffs(88, 32).addBox(-4.0F, -6.0F, 8.0F, 8.0F, 10.0F, 2.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 128);
    }

    public static LayerDefinition createSingularity() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        PartDefinition p_core = root.addOrReplaceChild("core", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -4.0F, -4.0F, 8.0F, 8.0F, 8.0F).texOffs(32, 0).addBox(-3.0F, -5.0F, -3.0F, 6.0F, 10.0F, 6.0F).texOffs(32, 16).addBox(-5.0F, -3.0F, -3.0F, 10.0F, 6.0F, 6.0F).texOffs(0, 16).addBox(-3.0F, -3.0F, -5.0F, 6.0F, 6.0F, 10.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        PartDefinition p_disk = root.addOrReplaceChild("disk", CubeListBuilder.create().texOffs(0, 32).addBox(6.0F, 0.0F, -2.0F, 4.0F, 1.0F, 4.0F).texOffs(16, 32).addBox(5.0F, 0.0F, 1.0F, 4.0F, 1.0F, 4.0F).texOffs(32, 32).addBox(4.0F, 0.0F, 4.0F, 4.0F, 1.0F, 4.0F).texOffs(48, 32).addBox(1.0F, 0.0F, 5.0F, 4.0F, 1.0F, 4.0F).texOffs(0, 37).addBox(-2.0F, 0.0F, 6.0F, 4.0F, 1.0F, 4.0F).texOffs(16, 37).addBox(-5.0F, 0.0F, 5.0F, 4.0F, 1.0F, 4.0F).texOffs(32, 37).addBox(-8.0F, 0.0F, 4.0F, 4.0F, 1.0F, 4.0F).texOffs(48, 37).addBox(-9.0F, 0.0F, 1.0F, 4.0F, 1.0F, 4.0F).texOffs(0, 42).addBox(-10.0F, 0.0F, -2.0F, 4.0F, 1.0F, 4.0F).texOffs(16, 42).addBox(-9.0F, 0.0F, -5.0F, 4.0F, 1.0F, 4.0F).texOffs(32, 42).addBox(-8.0F, 0.0F, -8.0F, 4.0F, 1.0F, 4.0F).texOffs(48, 42).addBox(-5.0F, 0.0F, -9.0F, 4.0F, 1.0F, 4.0F).texOffs(0, 47).addBox(-2.0F, 0.0F, -10.0F, 4.0F, 1.0F, 4.0F).texOffs(16, 47).addBox(1.0F, 0.0F, -9.0F, 4.0F, 1.0F, 4.0F).texOffs(32, 47).addBox(4.0F, 0.0F, -8.0F, 4.0F, 1.0F, 4.0F).texOffs(48, 47).addBox(5.0F, 0.0F, -5.0F, 4.0F, 1.0F, 4.0F).texOffs(0, 52).addBox(10.0F, 0.0F, 1.0F, 3.0F, 1.0F, 3.0F).texOffs(12, 52).addBox(7.0F, 0.0F, 6.0F, 3.0F, 1.0F, 3.0F).texOffs(24, 52).addBox(2.0F, 0.0F, 9.0F, 3.0F, 1.0F, 3.0F).texOffs(36, 52).addBox(-3.0F, 0.0F, 10.0F, 3.0F, 1.0F, 3.0F).texOffs(48, 52).addBox(-8.0F, 0.0F, 7.0F, 3.0F, 1.0F, 3.0F).texOffs(0, 56).addBox(-11.0F, 0.0F, 2.0F, 3.0F, 1.0F, 3.0F).texOffs(12, 56).addBox(-12.0F, 0.0F, -3.0F, 3.0F, 1.0F, 3.0F).texOffs(24, 56).addBox(-9.0F, 0.0F, -8.0F, 3.0F, 1.0F, 3.0F).texOffs(36, 56).addBox(-4.0F, 0.0F, -11.0F, 3.0F, 1.0F, 3.0F).texOffs(48, 56).addBox(1.0F, 0.0F, -12.0F, 3.0F, 1.0F, 3.0F).texOffs(0, 60).addBox(6.0F, 0.0F, -9.0F, 3.0F, 1.0F, 3.0F).texOffs(12, 60).addBox(9.0F, 0.0F, -4.0F, 3.0F, 1.0F, 3.0F), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 64, 64);
    }

}
