"""English text for Astralfall: names, tooltips, messages, the Astral Journal and the quests."""

NAMES = {
    # blocks
    'block.astralfall.meteorite_rock': 'Meteorite',
    'block.astralfall.cooled_meteorite': 'Cooled Meteorite',
    'block.astralfall.meteorite_bricks': 'Meteorite Bricks',
    'block.astralfall.starmetal_ore': 'Starmetal Ore',
    'block.astralfall.raw_starmetal_block': 'Block of Raw Starmetal',
    'block.astralfall.starmetal_block': 'Block of Starmetal',
    'block.astralfall.skyshard_block': 'Block of Skyshard',
    'block.astralfall.skyshard_cluster': 'Skyshard Cluster',
    'block.astralfall.void_stone': 'Void Stone',
    'block.astralfall.astral_bricks': 'Astral Bricks',
    'block.astralfall.cracked_astral_bricks': 'Cracked Astral Bricks',
    'block.astralfall.overgrown_astral_bricks': 'Overgrown Astral Bricks',
    'block.astralfall.chiseled_astral_bricks': 'Chiseled Astral Bricks',
    'block.astralfall.astral_brick_stairs': 'Astral Brick Stairs',
    'block.astralfall.astral_brick_slab': 'Astral Brick Slab',
    'block.astralfall.sealed_astral_bricks': 'Sealed Astral Bricks',
    'block.astralfall.astral_glass': 'Astral Glass',
    'block.astralfall.star_lock': 'Star Lock',
    'block.astralfall.astral_altar': 'Astral Altar',
    'block.astralfall.star_jar': 'Star Jar',
    'block.astralfall.fallen_star_block': 'Fallen Star',
    'block.astralfall.gravity_rune': 'Gravity Rune',
    'block.astralfall.starfire_vent': 'Starfire Vent',
    'block.astralfall.telescope_eyepiece': 'Telescope Eyepiece',
    # items
    'item.astralfall.astral_journal': 'Astral Journal',
    'item.astralfall.raw_starmetal': 'Raw Starmetal',
    'item.astralfall.starmetal_ingot': 'Starmetal Ingot',
    'item.astralfall.starmetal_nugget': 'Starmetal Nugget',
    'item.astralfall.skyshard': 'Skyshard',
    'item.astralfall.stardust': 'Stardust',
    'item.astralfall.void_essence': 'Void Essence',
    'item.astralfall.fallen_star': 'Fallen Star Shard',
    'item.astralfall.stellar_core': 'Stellar Core',
    'item.astralfall.eclipse_sigil': 'Eclipse Sigil',
    'item.astralfall.starblade': 'Starblade',
    'item.astralfall.comet_maul': 'Comet Maul',
    'item.astralfall.riftcaller': 'Riftcaller',
    'item.astralfall.constellation_bow': 'Constellation Bow',
    'item.astralfall.eclipse_greatsword': 'Eclipse Greatsword',
    'item.astralfall.starmetal_pickaxe': 'Starmetal Pickaxe',
    'item.astralfall.gravity_gauntlet': 'Gravity Gauntlet',
    'item.astralfall.singularity_grenade': 'Singularity Grenade',
    'item.astralfall.astral_compass': 'Astral Compass',
    'item.astralfall.starmetal_helmet': 'Starmetal Helmet',
    'item.astralfall.starmetal_chestplate': 'Starmetal Chestplate',
    'item.astralfall.starmetal_leggings': 'Starmetal Leggings',
    'item.astralfall.starmetal_boots': 'Starmetal Boots',
    'item.astralfall.voidwalker_helmet': 'Voidwalker Hood',
    'item.astralfall.voidwalker_chestplate': 'Voidwalker Robe',
    'item.astralfall.voidwalker_leggings': 'Voidwalker Leggings',
    'item.astralfall.voidwalker_boots': 'Voidwalker Boots',
    'item.astralfall.crown_of_astraeus': 'Crown of Astraeus',
    'item.astralfall.nebula_wings': 'Nebula Wings',
    'item.astralfall.astral_wisp_spawn_egg': 'Astral Wisp Spawn Egg',
    'item.astralfall.void_stalker_spawn_egg': 'Void Stalker Spawn Egg',
    'item.astralfall.meteorite_crawler_spawn_egg': 'Meteorite Crawler Spawn Egg',
    'item.astralfall.void_gazer_spawn_egg': 'Void Gazer Spawn Egg',
    'item.astralfall.astraeus_spawn_egg': 'Astraeus Spawn Egg',
    # entities
    'entity.astralfall.meteor': 'Meteor',
    'entity.astralfall.star_slash': 'Star Slash',
    'entity.astralfall.star_bolt': 'Star Bolt',
    'entity.astralfall.crystal_shard': 'Crystal Shard',
    'entity.astralfall.singularity': 'Singularity',
    'entity.astralfall.singularity_grenade': 'Singularity Grenade',
    'entity.astralfall.astral_wisp': 'Astral Wisp',
    'entity.astralfall.void_stalker': 'Void Stalker',
    'entity.astralfall.meteorite_crawler': 'Meteorite Crawler',
    'entity.astralfall.void_gazer': 'Void Gazer',
    'entity.astralfall.astraeus': 'Astraeus',
    'itemGroup.astralfall': 'Astralfall',
    'structure.astralfall.observatory': 'Shattered Observatory',
    'structure.astralfall.fallen_vessel': 'Fallen Vessel',
    'structure.astralfall.sky_shrine': 'Sky Shrine',
    'structure.astralfall.crater': 'Meteor Crater',
}

TOOLTIPS = {
    'item.astralfall.skyshard.desc.1': 'A crystal of frozen starlight.',
    'item.astralfall.stardust.desc.1': 'Wisps adore it.',
    'item.astralfall.void_essence.desc.1': 'Cold, and heavier than it looks.',
    'item.astralfall.fallen_star.desc.1': 'Still warm. It hums when you hold it.',
    'item.astralfall.fallen_star.desc.2': 'Needed for the Eclipse Sigil.',
    'item.astralfall.stellar_core.desc.1': 'The burning heart of Astraeus.',
    'item.astralfall.stellar_core.desc.2': 'Crafts Nebula Wings and the Eclipse Greatsword.',
    'item.astralfall.eclipse_sigil.desc.1': 'The stars go dark where this is raised.',
    'item.astralfall.eclipse_sigil.desc.2': 'Use on an Astral Altar to summon Astraeus.',
    'item.astralfall.eclipse_sigil.desc.3': 'Prepare first. There is no going back.',
    'item.astralfall.starblade.desc.1': 'Forged from the first metal to fall.',
    'item.astralfall.starblade.desc.2': 'Right-click: Star Slash  |  Sneak: Starlight Dash',
    'item.astralfall.starblade.desc.3': '+50% damage to void creatures',
    'item.astralfall.comet_maul.desc.1': 'The sky is your hammer.',
    'item.astralfall.comet_maul.desc.2': 'Hold right-click: call down a meteor',
    'item.astralfall.comet_maul.desc.3': 'Sneak + right-click: Ground Slam',
    'item.astralfall.riftcaller.desc.1': 'Cuts holes in the night.',
    'item.astralfall.riftcaller.desc.2': 'Right-click: open a black hole where you aim',
    'item.astralfall.riftcaller.desc.3': 'Hits siphon life back to you',
    'item.astralfall.constellation_bow.desc.1': 'Strung with starlight. Needs no arrows.',
    'item.astralfall.constellation_bow.desc.2': 'Fires up to 5 homing stars at full draw',
    'item.astralfall.constellation_bow.desc.3': 'Stars seek out hostile creatures',
    'item.astralfall.eclipse_greatsword.desc.1': 'A blade of black sun and corona fire.',
    'item.astralfall.eclipse_greatsword.desc.2': 'Hits charge the Eclipse; ignites foes',
    'item.astralfall.eclipse_greatsword.desc.3': 'Fully charged, right-click: Eclipse Nova',
    'item.astralfall.eclipse_greatsword.charge': 'Eclipse: %s',
    'item.astralfall.starmetal_pickaxe.desc.1': 'Mines a 3x3 area.',
    'item.astralfall.starmetal_pickaxe.desc.2': 'Sneak to mine a single block.',
    'item.astralfall.gravity_gauntlet.desc.1': 'Gravity is merely a suggestion.',
    'item.astralfall.gravity_gauntlet.desc.2': 'Hold right-click on a creature to lift it',
    'item.astralfall.gravity_gauntlet.desc.3': 'Release to throw  |  Sneak: rip out blocks',
    'item.astralfall.singularity_grenade.desc.1': 'Throw to open a black hole.',
    'item.astralfall.singularity_grenade.desc.2': 'It collapses with a violent shockwave.',
    'item.astralfall.astral_compass.desc.1': 'Right-click: locate and show the way',
    'item.astralfall.astral_compass.desc.2': 'Sneak + right-click: change target',
    'item.astralfall.crown_of_astraeus.desc.1': 'Stars fall on those you despise.',
    'item.astralfall.crown_of_astraeus.desc.2': 'Rains golden stars on nearby monsters',
    'item.astralfall.crown_of_astraeus.desc.3': 'Grants night vision',
    'item.astralfall.nebula_wings.desc.1': 'Glide trailing a nebula.',
    'item.astralfall.nebula_wings.desc.2': 'Works like an Elytra. Repair with Void Essence.',
}

MESSAGES = {
    'message.astralfall.star_lock.open': 'The seal shatters! %s stones crumble away...',
    'message.astralfall.star_lock.already_open': 'The Star Lock is already open.',
    'message.astralfall.star_lock.hint': 'An empty socket shaped like a star. It hungers for a Skyshard.',
    'message.astralfall.altar.hint': 'The altar awaits an Eclipse Sigil.',
    'message.astralfall.altar.busy': 'A ritual is already underway!',
    'message.astralfall.telescope.day': 'Only stars can be seen through the eyepiece. Wait for night.',
    'message.astralfall.telescope.cooldown': 'The sky is still. Try again later tonight.',
    'message.astralfall.telescope.star': 'You find a single bright star... it grows brighter... it is falling towards you!',
    'message.astralfall.starstorm.begin': 'The sky is breaking apart. A Starstorm has begun!',
    'message.astralfall.starstorm.end': 'The Starstorm has passed.',
    'message.astralfall.fallen_star': 'A star has fallen near %s, %s. Follow the pillar of light!',
    'message.astralfall.ritual.begin': 'The stars go dark, one by one...',
    'message.astralfall.boss.phase2': 'Astraeus: "You burn brightly. Let me swallow that light."',
    'message.astralfall.boss.phase3': 'Astraeus: "THE SKY ITSELF WILL FALL ON YOU!"',
    'message.astralfall.eclipse.not_ready': 'Eclipse charge %s/%s. Keep fighting!',
    'message.astralfall.gauntlet.nothing': 'Nothing to grab. Aim at a creature, or sneak at a block.',
    'message.astralfall.compass.mode': 'Target: %s',
    'message.astralfall.compass.none': 'No %s found nearby.',
    'message.astralfall.compass.found': '%s: %s blocks %s',
    'title.astralfall.starstorm': 'STARSTORM',
    'title.astralfall.starstorm.sub': 'The sky is falling',
    'title.astralfall.eclipse': 'THE ECLIPSE',
    'title.astralfall.eclipse.sub': 'Something vast is waking up',
    'title.astralfall.astraeus.sub': 'Devourer of Stars',
    'title.astralfall.victory': 'STAR DEVOURED',
    'title.astralfall.victory.sub': 'Dawn returns to the world',
    'command.astralfall.help.header': '=== Astralfall commands ===',
    'command.astralfall.help.kit': '/astralfall kit  - every weapon, armour set and gadget',
    'command.astralfall.help.starfall': '/astralfall starfall [n]  - meteors crash around you',
    'command.astralfall.help.fallenstar': '/astralfall fallenstar  - a golden Fallen Star lands ahead',
    'command.astralfall.help.starstorm': '/astralfall starstorm [stop]  - start a Starstorm',
    'command.astralfall.help.summon': '/astralfall summon  - begin the Eclipse ritual (boss)',
    'command.astralfall.help.build': '/astralfall build <observatory|fallen_vessel|sky_shrine|crater>',
    'command.astralfall.help.locate': '/astralfall locate <observatory|fallen_vessel|sky_shrine>',
    'command.astralfall.help.gallery': '/astralfall gallery  - line up every creature for filming',
    'command.astralfall.kit': 'Your star-forged kit has arrived.',
    'command.astralfall.starfall': '%s meteors are on their way...',
    'command.astralfall.fallenstar': 'Look up.',
    'command.astralfall.build': 'Built %s at %s %s %s',
    'command.astralfall.locate': 'Nearest %s: %s, %s (%s blocks away)',
    'command.astralfall.gallery': 'The Astralfall bestiary is on display.',
}

SUBTITLES = {
    'meteor_incoming': 'Meteor screams overhead', 'meteor_impact': 'Meteor impacts', 'star_chime': 'Star chimes',
    'starstorm': 'The sky cracks', 'wisp_ambient': 'Wisp twinkles', 'wisp_hurt': 'Wisp hurts', 'stalker_ambient': 'Something whispers',
    'stalker_scream': 'Void Stalker screams', 'stalker_blink': 'Void Stalker blinks', 'crawler_roll': 'Meteorite Crawler rumbles',
    'crawler_hurt': 'Meteorite Crawler cracks', 'gazer_charge': 'Gaze charges', 'gazer_beam': 'Gravity beam fires',
    'boss_roar': 'Astraeus roars', 'boss_summon': 'The stars go dark', 'boss_beam': 'Star Lance fires', 'boss_death': 'A star dies',
    'shockwave': 'Shockwave', 'singularity_hum': 'Singularity hums', 'singularity_collapse': 'Singularity collapses',
    'star_slash': 'Star Slash', 'star_bolt': 'Star Bolt fires', 'gravity_grab': 'Gravity grips', 'gravity_throw': 'Gravity hurls',
    'void_blink': 'Void blink', 'eclipse_nova': 'Eclipse Nova', 'vault_open': 'Ancient seal breaks',
}

# ---------------------------------------------------------------------------- the Astral Journal
# Book pages are short: about 14 lines of ~19 characters. \n forces a line break.
# Page 1 and 2 are the table of contents and are assembled in Java with clickable links.
JOURNAL = [
    # 3 - chapter 1
    "§5§lI. The Stars Fall§r\n\nI was the last astronomer of the Observatory. We watched the sky for a thousand years. Then the sky started watching back.\n\nThe stars are §lfalling§r.",
    "§5First steps§r\n\nAt §lnight§r, meteors streak across the sky and crash near you. Listen for the scream, watch for the fiery trail.\n\nRun to the crater before it cools.",
    # 5 - chapter 2
    "§5§lII. Starmetal§r\n\nA fresh crater holds glowing §6Meteorite§r, §9Starmetal Ore§r and §bSkyshard Clusters§r.\n\nYou need an §liron pickaxe§r or better. Old §lImpact Sites§r hide ore too.",
    "§5Smelting§r\n\nSmelt §9Raw Starmetal§r into §9Starmetal Ingots§r.\n\nSkyshards come from the crystal clusters. Break one into two §bStardust§r in a crafting grid.\n\nKeep both. Everything is made from them.",
    "§5First craft§r\n\n§lStarmetal Pickaxe§r:\nmines 3x3. Sneak to mine one block.\n\n§lStarblade§r:\nskyshard, ingot and stick in a column. Your first real weapon.",
    # 8 - chapter 3
    "§5§lIII. Armour§r\n\n§9Starmetal Armour§r (full set): you take §lno fall damage§r. Land from high up to release a §lMeteor Landing§r shockwave that flings enemies away.\n\nJump off cliffs on purpose.",
    "§5Voidwalker Armour§r\n\nWoven from §dVoid Essence§r.\nFull set:\n- Night vision\n- Void Stalkers ignore you\n- §lSneak in mid-air§r to blink forward through space.",
    # 10 - chapter 4
    "§5§lIV. Weapons§r\n\n§bStarblade§r\nRight-click: Star Slash, a piercing crescent.\nSneak: Starlight Dash through enemies.\n+50% vs void creatures.",
    "§6Comet Maul§r\nHold right-click, aim, release: a meteor crashes where you look.\nSneak: Ground Slam.\n\n§dRiftcaller§r\nRight-click opens a black hole. Hits heal you.",
    "§bConstellation Bow§r\nNo arrows. Full draw fires 5 homing stars.\n\n§dSingularity Grenade§r\nThrow it into a crowd.\n\n§9Gravity Gauntlet§r\nHold on a mob to lift it, let go to hurl it. Sneak on a block to throw that instead.",
    # 13 - chapter 5
    "§5§lV. Creatures§r\n\n§bAstral Wisp§r\nDrifts around fallen stars. Feed it §bStardust§r to tame it. It follows you, heals you and shoots gold stars.\nEmpty hand: sit/follow.\n§d1 in 30 are Prismatic!",
    "§5Void Stalker§r\n\n§lIt cannot move while you look at it.§r\nLook away and it runs. Ignore it too long and it appears §lbehind you§r.\n\nStarlight hurts it. Fades at sunrise.",
    "§6Meteorite Crawler§r\n\nHatches from dark meteors. It curls up and §lrolls§r at you.\n\nDodge so it hits a wall: it is §lstunned§r and takes §ldouble damage§r.\nRolling, it takes half.",
    "§5Void Gazer§r\n\nA floating eye. It glares for two seconds, then fires a §lgravity beam§r that throws you skyward.\n\nBreak line of sight while it charges. Pillars are your friends.",
    # 17 - chapter 6
    "§5§lVI. Places§r\n\nCraft an §bAstral Compass§r (compass + 4 skyshards). Right-click to find the nearest ruin; a trail of stars shows the way.\nSneak + use: change target.",
    "§5Shattered Observatory§r\n\nOur home, broken by a meteor. Guarded by stalkers and gazers.\n\n§lTraps:§r Gravity Runes fling you up (§lsneak§r across). Starfire Vents erupt.",
    "§5Secrets of the Observatory§r\n\nAt the top, the great §6telescope§r. Look through its eyepiece at night...\n\nThe §bStar Lock§r in the entrance hall hides our §lVault§r. It opens for a Skyshard.",
    "§5Fallen Vessel§r\n\nA ship that fell long ago, half buried in its own trench. Crawlers nest in the reactor.\nIts holds carry gravity tech.\n\n§5Sky Shrine§r\nAn island floating far above. Wings are kept there.",
    # 21 - chapter 7
    "§5§lVII. Starstorms§r\n\nSome nights the sky breaks: a §dStarstorm§r. Meteors fall every few seconds and shooting stars fill the sky.\n\nGreat for mining. Dangerous for everything else.",
    "§6Fallen Stars§r\n\nRarely a §6golden§r meteor falls. It leaves a Fallen Star under a pillar of light you can see from far away.\n\nMine it for a §6Fallen Star Shard§r. Wisps gather there.",
    # 23 - chapter 8
    "§5§lVIII. The Eclipse§r\n\nCraft the §5Eclipse Sigil§r:\n4 Void Essence\n4 Skyshards\n1 Fallen Star Shard\n\nUse it on the §lAstral Altar§r atop the Observatory, or on one you craft.",
    "§5Before the ritual§r\n\n- Full armour, healing\n- Starblade and bow\n- Gauntlet, grenades\n- A tamed wisp\n- Open ground, pillars to hide behind\n\nNight falls instantly.",
    "§4Astraeus§r §8(Phase I)§r\n\n§lMeteor Rain:§r keep moving.\n§lStar Lance:§r a sweeping beam; strafe or hide.\n§lCrystal Shards:§r homing; dodge or block.\n§lSlam:§r don't stay close.",
    "§4Gravity Collapse§r\nIt pulls you in, then explodes. Run outward the moment it spreads its arms.\n\n§4Phase II§r (50%)\nSummons stalkers and gazers. Opens black holes under you.",
    "§4Phase III§r (20%)\nThe sky itself falls: constant meteors, faster attacks.\n\nThe shards regrow. Destroy it before the dawn.\n\nWhen it dies, the sun rises.",
    # 28 - chapter 9
    "§5§lIX. Beyond§r\n\nAstraeus leaves:\n§6Stellar Core§r\n§6Eclipse Greatsword§r\n§6Crown of Astraeus§r\nand a fortune in starmetal.\n\nThe Crown rains golden stars on your enemies.",
    "§6Eclipse Greatsword§r\nEvery hit charges the eclipse. At 12, right-click for the §lEclipse Nova§r.\n\n§5Nebula Wings§r\nStellar Core + 4 Void Essence + 2 Phantom Membrane + 2 Skyshards.",
    # 30 - chapter 10
    "§5§lX. Quests§r\n\nOpen §lAdvancements§r (L) and choose the §5Astralfall§r tab: every step from your first meteor to the end, with rewards.\n\nLost this book? Craft a Book + Gold Nugget.",
    "§5For builders§r\n\nAstral bricks, glass, star jars and meteorite blocks are all craftable.\n\n§8Creative:§r §o/astralfall help§r lists showcase commands.\n\n§8Keep watching the sky.§r",
]

TOC = [  # (title, page index 1-based)
    ('I.   The Stars Fall', 3), ('II.  Starmetal', 5), ('III. Armour', 8), ('IV.  Weapons', 10),
    ('V.   Creatures', 13), ('VI.  Places', 17), ('VII. Starstorms', 21), ('VIII. The Eclipse', 23),
    ('IX.  Beyond', 28), ('X.   Quests', 30),
]

# ---------------------------------------------------------------------------- quests (advancements)
# id, parent, icon, title, description, frame, xp, reward_loot (or None), criteria spec
QUESTS = [
    ('root', None, 'astralfall:astral_journal', 'Astralfall', 'The stars are falling. Read your Astral Journal, then watch the night sky.', 'task', 0, 'journal', ('tick',)),
    ('first_light', 'root', 'astralfall:meteorite_rock', 'Starstruck', 'Mine something from a meteor crater', 'task', 20, 'first_light', ('any_item', ['astralfall:meteorite_rock', 'astralfall:raw_starmetal', 'astralfall:skyshard', 'astralfall:starmetal_ore'])),
    ('ingot', 'first_light', 'astralfall:starmetal_ingot', 'Forged in Starlight', 'Smelt a Starmetal Ingot', 'task', 25, None, ('item', 'astralfall:starmetal_ingot')),
    ('pickaxe', 'ingot', 'astralfall:starmetal_pickaxe', 'Three by Three', 'Craft a Starmetal Pickaxe', 'task', 30, None, ('item', 'astralfall:starmetal_pickaxe')),
    ('starblade', 'ingot', 'astralfall:starblade', 'A Blade of Starlight', 'Craft the Starblade', 'task', 40, None, ('item', 'astralfall:starblade')),
    ('starmetal_armor', 'ingot', 'astralfall:starmetal_chestplate', 'Meteor-Proof', 'Obtain a full set of Starmetal armour', 'goal', 60, None, ('all_items', ['astralfall:starmetal_helmet', 'astralfall:starmetal_chestplate', 'astralfall:starmetal_leggings', 'astralfall:starmetal_boots'])),
    ('comet_maul', 'starblade', 'astralfall:comet_maul', 'Call Down the Sky', 'Craft the Comet Maul', 'task', 50, None, ('item', 'astralfall:comet_maul')),
    ('compass', 'first_light', 'astralfall:astral_compass', 'Stargazer\'s Compass', 'Craft an Astral Compass', 'task', 30, None, ('item', 'astralfall:astral_compass')),
    ('fallen_star', 'first_light', 'astralfall:fallen_star', 'Catch a Falling Star', 'Obtain a Fallen Star Shard', 'goal', 60, 'fallen_star', ('item', 'astralfall:fallen_star')),
    ('star_jar', 'fallen_star', 'astralfall:star_jar', 'Bottled Starlight', 'Craft a Star Jar', 'task', 20, None, ('item', 'astralfall:star_jar')),
    ('wisp', 'fallen_star', 'astralfall:stardust', 'A Friend from the Stars', 'Tame an Astral Wisp with Stardust', 'goal', 60, None, ('tame', 'astralfall:astral_wisp')),
    ('stalker', 'first_light', 'astralfall:void_essence', 'Don\'t Blink', 'Defeat a Void Stalker', 'task', 50, None, ('kill', 'astralfall:void_stalker')),
    ('crawler', 'first_light', 'astralfall:raw_starmetal', 'Rock Bottom', 'Defeat a Meteorite Crawler', 'task', 40, None, ('kill', 'astralfall:meteorite_crawler')),
    ('gazer', 'stalker', 'astralfall:skyshard', 'Stare Down', 'Defeat a Void Gazer', 'task', 40, None, ('kill', 'astralfall:void_gazer')),
    ('observatory', 'compass', 'astralfall:chiseled_astral_bricks', 'The Shattered Observatory', 'Find the ruined Observatory', 'goal', 80, 'observatory', ('structure', 'astralfall:shattered_observatory')),
    ('vault', 'observatory', 'astralfall:constellation_bow', 'Written in the Stars', 'Open the Star Vault and claim the Constellation Bow', 'challenge', 120, None, ('item', 'astralfall:constellation_bow')),
    ('vessel', 'compass', 'astralfall:meteorite_bricks', 'Crash Site', 'Find a Fallen Vessel', 'goal', 60, None, ('structure', 'astralfall:fallen_vessel')),
    ('gauntlet', 'vessel', 'astralfall:gravity_gauntlet', 'Gravity Is Optional', 'Obtain the Gravity Gauntlet', 'goal', 60, None, ('item', 'astralfall:gravity_gauntlet')),
    ('shrine', 'compass', 'astralfall:star_jar', 'Heaven\'s Doorstep', 'Set foot on a Sky Shrine', 'challenge', 100, None, ('structure', 'astralfall:sky_shrine')),
    ('riftcaller', 'gazer', 'astralfall:riftcaller', 'A Hole in the Sky', 'Craft the Riftcaller', 'goal', 60, None, ('item', 'astralfall:riftcaller')),
    ('voidwalker', 'gazer', 'astralfall:voidwalker_helmet', 'Walker Between Stars', 'Obtain a full set of Voidwalker armour', 'goal', 80, None, ('all_items', ['astralfall:voidwalker_helmet', 'astralfall:voidwalker_chestplate', 'astralfall:voidwalker_leggings', 'astralfall:voidwalker_boots'])),
    ('sigil', 'fallen_star', 'astralfall:eclipse_sigil', 'The Eclipse Draws Near', 'Craft the Eclipse Sigil', 'goal', 100, None, ('item', 'astralfall:eclipse_sigil')),
    ('astraeus', 'sigil', 'astralfall:stellar_core', 'Devourer Devoured', 'Defeat Astraeus, Devourer of Stars', 'challenge', 500, None, ('kill', 'astralfall:astraeus')),
    ('greatsword', 'astraeus', 'astralfall:eclipse_greatsword', 'Wielder of the Eclipse', 'Obtain the Eclipse Greatsword', 'goal', 100, None, ('item', 'astralfall:eclipse_greatsword')),
    ('crown', 'astraeus', 'astralfall:crown_of_astraeus', 'Crowned by the Cosmos', 'Obtain the Crown of Astraeus', 'goal', 100, None, ('item', 'astralfall:crown_of_astraeus')),
    ('wings', 'astraeus', 'astralfall:nebula_wings', 'Nebula Flight', 'Craft Nebula Wings from a Stellar Core', 'challenge', 150, None, ('item', 'astralfall:nebula_wings')),
]
