package com.oathbound.registry;

import com.oathbound.entity.boss.*;
import com.oathbound.entity.mob.*;
import com.oathbound.entity.npc.*;
import net.minecraft.core.BlockPos;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.EntitySpawnReason;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.SpawnPlacementTypes;
import net.minecraft.world.entity.monster.Monster;
import net.minecraft.world.level.ServerLevelAccessor;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.event.entity.SpawnPlacementRegisterEvent;

/** GENERATED by tools/oath/roster.py: attributes and spawn rules for the wider roster. */
public final class RosterRegistry {
    private RosterRegistry() {}

    public static void attributes(EntityAttributeCreationEvent event) {
        event.put(ModEntities.GLIMMERFAWN.get(), GlimmerfawnEntity.createAttributes().build());
        event.put(ModEntities.DUSKHARE.get(), DuskhareEntity.createAttributes().build());
        event.put(ModEntities.MOSSBACK_TORTOISE.get(), MossbackTortoiseEntity.createAttributes().build());
        event.put(ModEntities.LUMEN_BEETLE.get(), LumenBeetleEntity.createAttributes().build());
        event.put(ModEntities.TIDEWADER.get(), TidewaderEntity.createAttributes().build());
        event.put(ModEntities.THORNBACK_BOAR.get(), ThornbackBoarEntity.createAttributes().build());
        event.put(ModEntities.STONEWARDEN.get(), StonewardenEntity.createAttributes().build());
        event.put(ModEntities.RUNEWISP.get(), RunewispEntity.createAttributes().build());
        event.put(ModEntities.DROWNED_CHOIRMONK.get(), DrownedChoirmonkEntity.createAttributes().build());
        event.put(ModEntities.MIRE_HAG.get(), MireHagEntity.createAttributes().build());
        event.put(ModEntities.GRAVE_CRAWLER.get(), GraveCrawlerEntity.createAttributes().build());
        event.put(ModEntities.GLOAM_STALKER.get(), GloamStalkerEntity.createAttributes().build());
        event.put(ModEntities.SHADE_WRAITH.get(), ShadeWraithEntity.createAttributes().build());
        event.put(ModEntities.LUMENITE_MITE.get(), LumeniteMiteEntity.createAttributes().build());
        event.put(ModEntities.ASHEN_REVENANT.get(), AshenRevenantEntity.createAttributes().build());
        event.put(ModEntities.ELDERHORN.get(), ElderhornEntity.createAttributes().build());
        event.put(ModEntities.BOG_MOTHER.get(), BogMotherEntity.createAttributes().build());
        event.put(ModEntities.CINDER_COLOSSUS.get(), CinderColossusEntity.createAttributes().build());
        event.put(ModEntities.GLIMMERSTAG.get(), GlimmerstagEntity.createAttributes().build());
        event.put(ModEntities.LANTERNGUARD_PILGRIM.get(), LanternguardPilgrimEntity.createAttributes().build());
    }

    public static void spawnPlacements(SpawnPlacementRegisterEvent event) {
        event.register(ModEntities.GLIMMERFAWN.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            WildAnimal::checkWildSpawn, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.DUSKHARE.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            WildAnimal::checkWildSpawn, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.MOSSBACK_TORTOISE.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            WildAnimal::checkShoreSpawn, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.LUMEN_BEETLE.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            WildAnimal::checkCaveSpawn, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.TIDEWADER.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            WildAnimal::checkShoreSpawn, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.THORNBACK_BOAR.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            WildAnimal::checkWildSpawn, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.STONEWARDEN.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            WildAnimal::checkWildSpawn, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.RUNEWISP.get(), SpawnPlacementTypes.NO_RESTRICTIONS, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            RunewispEntity::checkWispSpawn, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.DROWNED_CHOIRMONK.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            Monster::checkMonsterSpawnRules, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.MIRE_HAG.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            Monster::checkMonsterSpawnRules, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.GRAVE_CRAWLER.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            Monster::checkMonsterSpawnRules, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.GLOAM_STALKER.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            Monster::checkMonsterSpawnRules, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.SHADE_WRAITH.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            Monster::checkMonsterSpawnRules, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.LUMENITE_MITE.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            RosterRegistry::checkMiteSpawn, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.ASHEN_REVENANT.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            Monster::checkMonsterSpawnRules, SpawnPlacementRegisterEvent.Operation.REPLACE);
        event.register(ModEntities.GLIMMERSTAG.get(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES,
            WildAnimal::checkWildSpawn, SpawnPlacementRegisterEvent.Operation.REPLACE);
    }

    /** Lumenite mites: monster rules, and only deep underground. */
    public static boolean checkMiteSpawn(EntityType<? extends Monster> type, ServerLevelAccessor level, EntitySpawnReason reason, BlockPos pos, RandomSource random) {
        return pos.getY() < 40 && Monster.checkMonsterSpawnRules(type, level, reason, pos, random);
    }
}
